const fs = require('fs');

const newKeys = {
  en: {
    // Target / facility format
    target_label: "Target",
    assigned_hospital: "Assigned Hospital",
    referral_link: "Referral Link",
    // Clinician types
    clinician_asha_frontline: "ASHA Frontline Worker",
    clinician_hospital_cmo: "Hospital CMO / Duty Officer",
    clinician_ml_engine: "Automated ML Engine",
    clinician_system_user: "System User",
    // Severity filter buttons
    sev_all: "ALL",
    sev_critical: "CRITICAL",
    sev_warning: "WARNING",
    sev_info: "INFO",
    // Policies section
    policies_title: "Regional Routing Governance Policies",
    policies_subtitle: "Algorithmic rules enforcing transit corridors and hospital referral thresholds.",
    pol_active_enforced: "ACTIVE ENFORCED",
    pol01_name: "Golden Hour Max Transit Radius",
    pol01_desc: "Maximum allowable ground travel time before triggering mandatory air/hub escalation",
    pol02_name: "ICU Auto-Divert Threshold",
    pol02_desc: "Automatically marks tertiary receiving center as Standby when obstetrics ICU hits capacity",
    pol03_name: "Night Emergency Transit Multiplier",
    pol03_desc: "Adjusts Haversine estimated routing velocity between 20:00 and 06:00 IST",
    pol04_name: "Pediatric VIPER Auto-Escalate",
    pol04_desc: "Auto-locks 108 emergency vehicle with pediatric oxygen & SNCU pre-arrival notification",
    // RBAC section
    rbac_title: "Clinicians & Role-Based Access Control (RBAC)",
    rbac_subtitle: "System authorization boundaries across ASHA, Hospital CMO, and DHO Command tiers.",
    permissions_label: "Permissions",
    rbac_role_asha: "ASHA / ANM Frontline Worker",
    rbac_perm_asha: "Maternal Triage, Child VIPER, Cardio Screening, 108 Beacon",
    rbac_count_asha: "1,842 Active",
    rbac_role_hospital: "Hospital Staff / CMO",
    rbac_perm_hospital: "Live Bed/NICU/Blood Capacity Editor, Patient Admissions, Clinical Analytics",
    rbac_count_hospital: "165 Facilities",
    rbac_role_dho: "DHO Command Director",
    rbac_perm_dho: "Full Matrix Command, Audit Export, Policy Override, Emergency Broadcast",
    rbac_count_dho: "36 Districts",
  },
  hi: {
    target_label: "लक्ष्य",
    assigned_hospital: "नियुक्त अस्पताल",
    referral_link: "रेफरल लिंक",
    clinician_asha_frontline: "आशा फ्रंटलाइन कार्यकर्ता",
    clinician_hospital_cmo: "अस्पताल CMO / ड्यूटी अधिकारी",
    clinician_ml_engine: "स्वचालित ML इंजन",
    clinician_system_user: "सिस्टम उपयोगकर्ता",
    sev_all: "सभी",
    sev_critical: "गंभीर",
    sev_warning: "चेतावनी",
    sev_info: "सूचना",
    policies_title: "क्षेत्रीय रूटिंग शासन नीतियाँ",
    policies_subtitle: "ट्रांजिट कॉरिडोर और अस्पताल रेफरल सीमाओं को लागू करने वाले एल्गोरिदमिक नियम।",
    pol_active_enforced: "सक्रिय लागू",
    pol01_name: "गोल्डन आवर अधिकतम ट्रांजिट त्रिज्या",
    pol01_desc: "अनिवार्य एयर/हब एस्केलेशन से पहले अधिकतम अनुमेय भूमि यात्रा समय",
    pol02_name: "आईसीयू ऑटो-डाइवर्ट सीमा",
    pol02_desc: "जब प्रसूति ICU क्षमता तक पहुंचे तो तृतीयक प्राप्ति केंद्र को स्टैंडबाय के रूप में चिह्नित करता है",
    pol03_name: "रात्रि आपातकालीन ट्रांजिट गुणक",
    pol03_desc: "20:00 और 06:00 IST के बीच हेवरसाइन अनुमानित रूटिंग वेग को समायोजित करता है",
    pol04_name: "पीडियाट्रिक VIPER ऑटो-एस्केलेट",
    pol04_desc: "पीडियाट्रिक ऑक्सीजन और SNCU पूर्व-आगमन अधिसूचना के साथ 108 आपातकालीन वाहन लॉक करता है",
    rbac_title: "चिकित्सक और भूमिका-आधारित पहुँच नियंत्रण (RBAC)",
    rbac_subtitle: "आशा, अस्पताल CMO और DHO कमांड स्तरों पर सिस्टम प्राधिकरण सीमाएँ।",
    permissions_label: "अनुमतियाँ",
    rbac_role_asha: "आशा / ANM फ्रंटलाइन कार्यकर्ता",
    rbac_perm_asha: "मातृ ट्राइज, बाल VIPER, कार्डियो स्क्रीनिंग, 108 बीकन",
    rbac_count_asha: "1,842 सक्रिय",
    rbac_role_hospital: "अस्पताल स्टाफ / CMO",
    rbac_perm_hospital: "लाइव बेड/NICU/रक्त क्षमता संपादक, रोगी प्रवेश, क्लिनिकल एनालिटिक्स",
    rbac_count_hospital: "165 सुविधाएं",
    rbac_role_dho: "DHO कमांड निदेशक",
    rbac_perm_dho: "पूर्ण मैट्रिक्स कमांड, ऑडिट एक्सपोर्ट, नीति ओवरराइड, आपातकालीन प्रसारण",
    rbac_count_dho: "36 जिले",
  },
  mr: {
    target_label: "लक्ष्य",
    assigned_hospital: "नियुक्त रुग्णालय",
    referral_link: "रेफरल लिंक",
    clinician_asha_frontline: "आशा फ्रंटलाइन कार्यकर्ता",
    clinician_hospital_cmo: "रुग्णालय CMO / ड्युटी अधिकारी",
    clinician_ml_engine: "स्वयंचलित ML इंजिन",
    clinician_system_user: "सिस्टम वापरकर्ता",
    sev_all: "सर्व",
    sev_critical: "गंभीर",
    sev_warning: "इशारा",
    sev_info: "माहिती",
    policies_title: "प्रादेशिक रूटिंग शासन धोरणे",
    policies_subtitle: "ट्रान्झिट कॉरिडोर आणि रुग्णालय रेफरल उंबरठे लागू करणारे अल्गोरिदमिक नियम।",
    pol_active_enforced: "सक्रिय लागू",
    pol01_name: "गोल्डन आवर कमाल ट्रान्झिट त्रिज्या",
    pol01_desc: "अनिवार्य एअर/हब एस्केलेशनपूर्वी कमाल अनुमत जमीन प्रवास वेळ",
    pol02_name: "ICU ऑटो-डायव्हर्ट उंबरठा",
    pol02_desc: "जेव्हा प्रसूती ICU क्षमतेपर्यंत पोहोचते तेव्हा तृतीयक केंद्र स्टँडबायवर चिन्हांकित करते",
    pol03_name: "रात्रीचा आपत्कालीन ट्रान्झिट गुणक",
    pol03_desc: "20:00 ते 06:00 IST दरम्यान हेवरसाइन अंदाजित रूटिंग वेग समायोजित करतो",
    pol04_name: "बालरोग VIPER ऑटो-एस्केलेट",
    pol04_desc: "बालरोग ऑक्सिजन आणि SNCU पूर्व-आगमन सूचनेसह 108 आपत्कालीन वाहन लॉक करतो",
    rbac_title: "चिकित्सक आणि भूमिका-आधारित प्रवेश नियंत्रण (RBAC)",
    rbac_subtitle: "आशा, रुग्णालय CMO आणि DHO कमांड स्तरांवर सिस्टम प्राधिकरण सीमा।",
    permissions_label: "परवानग्या",
    rbac_role_asha: "आशा / ANM फ्रंटलाइन कार्यकर्ता",
    rbac_perm_asha: "मातृ ट्रायज, बाल VIPER, कार्डियो स्क्रीनिंग, 108 बीकन",
    rbac_count_asha: "1,842 सक्रिय",
    rbac_role_hospital: "रुग्णालय स्टाफ / CMO",
    rbac_perm_hospital: "थेट बेड/NICU/रक्त क्षमता संपादक, रुग्ण प्रवेश, क्लिनिकल अॅनालिटिक्स",
    rbac_count_hospital: "165 सुविधा",
    rbac_role_dho: "DHO कमांड संचालक",
    rbac_perm_dho: "पूर्ण मॅट्रिक्स कमांड, ऑडिट एक्सपोर्ट, धोरण ओव्हरराइड, आपत्कालीन प्रसारण",
    rbac_count_dho: "36 जिल्हे",
  },
  ta: {
    target_label: "இலக்கு",
    assigned_hospital: "நியமிக்கப்பட்ட மருத்துவமனை",
    referral_link: "பரிந்துரை இணைப்பு",
    clinician_asha_frontline: "ஆஷா முன்னணி பணியாளர்",
    clinician_hospital_cmo: "மருத்துவமனை CMO / கடமை அதிகாரி",
    clinician_ml_engine: "தானியங்கி ML இயந்திரம்",
    clinician_system_user: "கணினி பயனர்",
    sev_all: "அனைத்தும்",
    sev_critical: "அதிக தீவிரம்",
    sev_warning: "எச்சரிக்கை",
    sev_info: "தகவல்",
    policies_title: "பிராந்திய ரூட்டிங் நிர்வாக கொள்கைகள்",
    policies_subtitle: "போக்குவரத்து தாழ்வாரங்கள் மற்றும் மருத்துவமனை பரிந்துரை வரம்புகளை செயல்படுத்தும் வழிமுறை விதிகள்.",
    pol_active_enforced: "செயல்படுத்தப்பட்டது",
    pol01_name: "கோல்டன் ஹவர் அதிகபட்ச போக்குவரத்து ஆரம்",
    pol01_desc: "கட்டாய காற்று/மையத்தில் தீவிரமாக்குவதற்கு முன் அதிகபட்ச அனுமதிக்கப்பட்ட தரை பயண நேரம்",
    pol02_name: "ICU தானியங்கி திசைதிருப்பல் வரம்பு",
    pol02_desc: "மகப்பேறு ICU திறனை அடையும்போது மூன்றாம் நிலை மையத்தை காத்திருப்பாக குறிக்கிறது",
    pol03_name: "இரவு அவசர போக்குவரத்து பெருக்கி",
    pol03_desc: "20:00 மற்றும் 06:00 IST இடையில் ஹவர்சைன் மதிப்பிட்ட ரூட்டிங் வேகத்தை சரிசெய்கிறது",
    pol04_name: "குழந்தை VIPER தானியங்கி தீவிரமாக்கல்",
    pol04_desc: "குழந்தை ஆக்சிஜன் & SNCU முன்-வருகை அறிவிப்புடன் 108 அவசர வாகனத்தை பூட்டுகிறது",
    rbac_title: "மருத்துவர்கள் & பங்கு அடிப்படையிலான அணுகல் கட்டுப்பாடு (RBAC)",
    rbac_subtitle: "ASHA, மருத்துவமனை CMO மற்றும் DHO கட்டளை அடுக்குகளில் கணினி அங்கீகார எல்லைகள்.",
    permissions_label: "அனுமதிகள்",
    rbac_role_asha: "ஆஷா / ANM முன்னணி பணியாளர்",
    rbac_perm_asha: "தாய்வழி ட்ரையேஜ், குழந்தை VIPER, கார்டியோ திரையிடல், 108 பிரகாசம்",
    rbac_count_asha: "1,842 செயல்பாட்டில்",
    rbac_role_hospital: "மருத்துவமனை ஊழியர் / CMO",
    rbac_perm_hospital: "நேரடி படுக்கை/NICU/இரத்த திறன் திருத்தி, நோயாளி சேர்க்கை, மருத்துவ பகுப்பாய்வு",
    rbac_count_hospital: "165 வசதிகள்",
    rbac_role_dho: "DHO கட்டளை இயக்குநர்",
    rbac_perm_dho: "முழு மேட்ரிக்ஸ் கட்டளை, தணிக்கை ஏற்றுமதி, கொள்கை மேலெழுதல், அவசர ஒளிபரப்பு",
    rbac_count_dho: "36 மாவட்டங்கள்",
  }
};

let code = fs.readFileSync('src/context/LanguageContext.jsx', 'utf8');

['en', 'mr', 'hi', 'ta'].forEach(lang => {
  const keyStr = Object.entries(newKeys[lang]).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
  code = code.replace(`${lang}: {`, `${lang}: {\n${keyStr}`);
});

fs.writeFileSync('src/context/LanguageContext.jsx', code);
console.log('Round 5 translation keys injected!');
