const fs = require('fs');

const newKeys = {
  en: {
    login_platform_subtitle: "National Maternal & Child Health Intelligence Platform",
    login_asha_register_subtitle: "Frontline ASHA Worker Self-Registration & Onboarding Grid",
    login_existing_staff: "Existing Staff Sign In",
    login_register_asha: "Register New ASHA",
    login_preconfigured_accounts: "Pre-Configured Official Accounts:",
    login_one_click_test: "1-click to test",
    login_asha_worker: "ASHA Worker",
    login_hospital_cmo: "Hospital CMO",
    login_dho_command: "DHO Command",
    login_clinician_id: "Clinician ID / Mobile Number",
    login_clinician_placeholder: "e.g. 9876543210 or staff ID",
    login_security_key: "Security Key / Password",
    login_forgot_key: "Forgot Key?",
    login_enter_key_placeholder: "Enter security key / PIN",
    login_verify_device: "Verify device for 30 days",
    login_authenticating: "Authenticating...",
    login_authenticate_btn: "Authenticate Access",
    login_encrypted_session: "End-to-End Encrypted Session • Ayushman Bharat Digital Health",
    facility_label: "Facility",
    maharashtra_command_hq: "Maharashtra Command HQ",
    switch_authenticated_persona: "Switch Authenticated Persona",
    select_portal_authenticate: "Select Portal & Authenticate",
    custom_credentials_login: "Custom Credentials Login",
    enter_security_key_verify: "Enter security key / PIN to verify access",
    clinician_staff_id: "Clinician / Staff ID",
    security_key_access_pin: "Security Key / Access PIN",
    official_password: "Official Password",
    autofill_key: "Autofill Key",
    verifying_credentials: "Verifying Credentials...",
    verify_access_portal: "Verify Access & Open Portal",
    dest_hospital_details: "Destination Hospital Details",
    status_ready: "READY",
    labor_ot_standby: "Labor OT Standby",
    hosp_edit_details: "Edit Details",
  },
  hi: {
    login_platform_subtitle: "राष्ट्रीय मातृ एवं शिशु स्वास्थ्य बुद्धिमत्ता प्लेटफ़ॉर्म",
    login_asha_register_subtitle: "फ्रंटलाइन आशा कार्यकर्ता स्व-पंजीकरण और ऑनबोर्डिंग ग्रिड",
    login_existing_staff: "मौजूदा स्टाफ साइन इन",
    login_register_asha: "नई आशा पंजीकृत करें",
    login_preconfigured_accounts: "पूर्व-कॉन्फ़िगर किए गए आधिकारिक खाते:",
    login_one_click_test: "1-क्लिक से परीक्षण",
    login_asha_worker: "आशा कार्यकर्ता",
    login_hospital_cmo: "अस्पताल सीएमओ",
    login_dho_command: "डीएचओ कमान",
    login_clinician_id: "क्लिनिशियन आईडी / मोबाइल नंबर",
    login_clinician_placeholder: "जैसे 9876543210 या स्टाफ आईडी",
    login_security_key: "सुरक्षा कुंजी / पासवर्ड",
    login_forgot_key: "कुंजी भूल गए?",
    login_enter_key_placeholder: "सुरक्षा कुंजी / पिन दर्ज करें",
    login_verify_device: "30 दिनों के लिए डिवाइस सत्यापित करें",
    login_authenticating: "प्रमाणीकरण हो रहा है...",
    login_authenticate_btn: "पहुँच प्रमाणित करें",
    login_encrypted_session: "एंड-टू-एंड एन्क्रिप्टेड सत्र • आयुष्मान भारत डिजिटल स्वास्थ्य",
    facility_label: "सुविधा",
    maharashtra_command_hq: "महाराष्ट्र कमान मुख्यालय",
    switch_authenticated_persona: "प्रमाणित पहचान बदलें",
    select_portal_authenticate: "पोर्टल चुनें और प्रमाणित करें",
    custom_credentials_login: "कस्टम क्रेडेंशियल लॉगिन",
    enter_security_key_verify: "पहुँच सत्यापित करने के लिए सुरक्षा कुंजी / पिन दर्ज करें",
    clinician_staff_id: "क्लिनिशियन / स्टाफ आईडी",
    security_key_access_pin: "सुरक्षा कुंजी / पहुँच पिन",
    official_password: "आधिकारिक पासवर्ड",
    autofill_key: "कुंजी स्वत: भरें",
    verifying_credentials: "क्रेडेंशियल सत्यापित हो रहे हैं...",
    verify_access_portal: "पहुँच सत्यापित करें और पोर्टल खोलें",
    dest_hospital_details: "गंतव्य अस्पताल विवरण",
    status_ready: "तैयार",
    labor_ot_standby: "प्रसव ओटी स्टैंडबाय",
    hosp_edit_details: "विवरण संपादित करें",
  },
  mr: {
    login_platform_subtitle: "राष्ट्रीय माता व बाल आरोग्य बुद्धिमत्ता प्लॅटफॉर्म",
    login_asha_register_subtitle: "फ्रंटलाइन आशा कार्यकर्ता स्व-नोंदणी आणि ऑनबोर्डिंग ग्रिड",
    login_existing_staff: "विद्यमान कर्मचारी साइन इन",
    login_register_asha: "नवीन आशा नोंदणी करा",
    login_preconfigured_accounts: "पूर्व-कॉन्फिगर केलेले अधिकृत खाते:",
    login_one_click_test: "1-क्लिकने चाचणी",
    login_asha_worker: "आशा कार्यकर्ता",
    login_hospital_cmo: "रुग्णालय CMO",
    login_dho_command: "DHO कमांड",
    login_clinician_id: "क्लिनिशियन आयडी / मोबाइल नंबर",
    login_clinician_placeholder: "उदा. 9876543210 किंवा स्टाफ आयडी",
    login_security_key: "सुरक्षा की / पासवर्ड",
    login_forgot_key: "की विसरलात?",
    login_enter_key_placeholder: "सुरक्षा की / पिन प्रविष्ट करा",
    login_verify_device: "30 दिवसांसाठी डिव्हाइस सत्यापित करा",
    login_authenticating: "प्रमाणीकरण होत आहे...",
    login_authenticate_btn: "प्रवेश प्रमाणित करा",
    login_encrypted_session: "एंड-टू-एंड एन्क्रिप्टेड सत्र • आयुष्मान भारत डिजिटल आरोग्य",
    facility_label: "सुविधा",
    maharashtra_command_hq: "महाराष्ट्र कमांड मुख्यालय",
    switch_authenticated_persona: "प्रमाणित ओळख बदला",
    select_portal_authenticate: "पोर्टल निवडा आणि प्रमाणित करा",
    custom_credentials_login: "कस्टम क्रेडेन्शियल लॉगिन",
    enter_security_key_verify: "प्रवेश सत्यापित करण्यासाठी सुरक्षा की / पिन प्रविष्ट करा",
    clinician_staff_id: "क्लिनिशियन / स्टाफ आयडी",
    security_key_access_pin: "सुरक्षा की / प्रवेश पिन",
    official_password: "अधिकृत पासवर्ड",
    autofill_key: "की स्वयंचलितपणे भरा",
    verifying_credentials: "क्रेडेन्शियल सत्यापित होत आहेत...",
    verify_access_portal: "प्रवेश सत्यापित करा आणि पोर्टल उघडा",
    dest_hospital_details: "गंतव्य रुग्णालय तपशील",
    status_ready: "तयार",
    labor_ot_standby: "प्रसव OT स्टँडबाय",
    hosp_edit_details: "तपशील संपादित करा",
  },
  ta: {
    login_platform_subtitle: "தேசிய தாய் மற்றும் குழந்தை சுகாதார நுண்ணறிவு தளம்",
    login_asha_register_subtitle: "முன்னணி ஆஷா பணியாளர் சுய-பதிவு மற்றும் ஒன்போர்டிங் கட்டம்",
    login_existing_staff: "தற்போதைய ஊழியர் உள்நுழைவு",
    login_register_asha: "புதிய ஆஷாவை பதிவு செய்யுங்கள்",
    login_preconfigured_accounts: "முன்-கட்டமைக்கப்பட்ட அதிகாரப்பூர்வ கணக்குகள்:",
    login_one_click_test: "1-கிளிக்கில் சோதனை",
    login_asha_worker: "ஆஷா பணியாளர்",
    login_hospital_cmo: "மருத்துவமனை CMO",
    login_dho_command: "DHO கட்டளை",
    login_clinician_id: "மருத்துவர் ஐடி / மொபைல் எண்",
    login_clinician_placeholder: "எ.கா. 9876543210 அல்லது ஊழியர் ஐடி",
    login_security_key: "பாதுகாப்பு சாவி / கடவுச்சொல்",
    login_forgot_key: "சாவி மறந்துவிட்டீர்களா?",
    login_enter_key_placeholder: "பாதுகாப்பு சாவி / PIN ஐ உள்ளிடுங்கள்",
    login_verify_device: "30 நாட்களுக்கு சாதனத்தை சரிபார்க்கவும்",
    login_authenticating: "அங்கீகரிக்கப்படுகிறது...",
    login_authenticate_btn: "அணுகலை அங்கீகரிக்கவும்",
    login_encrypted_session: "எண்ட்-டு-எண்ட் என்க்ரிப்ட் செய்யப்பட்ட அமர்வு • ஆயுஷ்மான் பாரத் டிஜிட்டல் சுகாதாரம்",
    facility_label: "வசதி",
    maharashtra_command_hq: "மகாராஷ்டிரா கட்டளை தலைமையகம்",
    switch_authenticated_persona: "அங்கீகரிக்கப்பட்ட பெர்சோனாவை மாற்றுங்கள்",
    select_portal_authenticate: "போர்டலை தேர்ந்தெடுத்து அங்கீகரிக்கவும்",
    custom_credentials_login: "தனிப்பயன் நற்சான்றிதழ் உள்நுழைவு",
    enter_security_key_verify: "அணுகலை சரிபார்க்க பாதுகாப்பு சாவி / PIN ஐ உள்ளிடுங்கள்",
    clinician_staff_id: "மருத்துவர் / ஊழியர் ஐடி",
    security_key_access_pin: "பாதுகாப்பு சாவி / அணுகல் PIN",
    official_password: "அதிகாரப்பூர்வ கடவுச்சொல்",
    autofill_key: "சாவியை தானாக நிரப்பு",
    verifying_credentials: "நற்சான்றிதழ்கள் சரிபார்க்கப்படுகின்றன...",
    verify_access_portal: "அணுகலை சரிபார்த்து போர்டலைத் திறக்கவும்",
    dest_hospital_details: "இலக்கு மருத்துவமனை விவரங்கள்",
    status_ready: "தயார்",
    labor_ot_standby: "பிரசவ OT காத்திருக்கிறது",
    hosp_edit_details: "விவரங்களை திருத்து",
  }
};

let code = fs.readFileSync('src/context/LanguageContext.jsx', 'utf8');

['en', 'mr', 'hi', 'ta'].forEach(lang => {
  const keyStr = Object.entries(newKeys[lang]).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join('\n');
  code = code.replace(`${lang}: {`, `${lang}: {\n${keyStr}`);
});

fs.writeFileSync('src/context/LanguageContext.jsx', code);
console.log('All new translation keys injected!');
