"""
Seeds the database with real government hospitals across Tamil Nadu and
Maharashtra (sourced from OpenStreetMap, filtered to government facilities,
deduplicated, and district-assigned).

All names, districts, states, and coordinates are REAL. All capacity numbers
(beds, NICU, blood stock, surgeon status) are DETERMINISTIC MOCK DATA -
generated from a hash of each hospital's name so the same hospital always
gets the same demo numbers on every re-seed. No public source provides live
hospital inventory data anywhere in India - this is intentional, matching
the realistic self-reporting deployment model this system is designed for.

Run this once (or re-run anytime to reset) from the backend/ folder:
    python3 -m app.seed_hospitals
"""
from app.db import Hospital, SessionLocal, init_db

HOSPITALS = [   {   'beds_available': 14,
        'district': 'Chennai',
        'lat': 13.0336624,
        'lng': 80.2572467,
        'name': 'Corporation Hospital',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 6,
        'stock_o_neg': 0,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 9,
        'district': 'Chennai',
        'lat': 13.0720996,
        'lng': 80.2589871,
        'name': 'Govt Maternity Hospital',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 1,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 8,
        'stock_o_neg': 4,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 6,
        'district': 'Chengalpattu',
        'lat': 12.5274531,
        'lng': 80.1631378,
        'name': 'Govt Primary Health Centre',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 0,
        'stock_o_neg': 4,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Chengalpattu'},
    {   'beds_available': 19,
        'district': 'Erode',
        'lat': 11.4432595,
        'lng': 77.6941951,
        'name': 'Govt hospital',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 8,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Erode'},
    {   'beds_available': 23,
        'district': 'Villupuram',
        'lat': 11.9933796,
        'lng': 79.5174212,
        'name': 'Goverment medical college & hospital, Villupuram',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 1,
        'stock_o_neg': 1,
        'stock_o_pos': 2,
        'surgeon_on_duty': False,
        'village_area': 'Villupuram'},
    {   'beds_available': 8,
        'district': 'Ranipet',
        'lat': 13.0995425,
        'lng': 79.5324922,
        'name': 'paranji Govt Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 9,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 6,
        'stock_o_neg': 3,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Ranipet'},
    {   'beds_available': 24,
        'district': 'Coimbatore',
        'lat': 11.0827084,
        'lng': 76.9427442,
        'name': 'Government Urban Primary Health Center',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 8,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 0,
        'surgeon_on_duty': False,
        'village_area': 'Coimbatore'},
    {   'beds_available': 10,
        'district': 'Tiruchirappalli',
        'lat': 10.7857499,
        'lng': 78.7251483,
        'name': 'central Government railway Hospital',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 3,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 3,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Tiruchirappalli'},
    {   'beds_available': 13,
        'district': 'Chennai',
        'lat': 12.9241666,
        'lng': 80.1274453,
        'name': 'government child health center',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 3,
        'stock_o_neg': 5,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 10,
        'district': 'Tiruvallur',
        'lat': 13.0849714,
        'lng': 79.6647558,
        'name': 'Arakkonam Government General Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 2,
        'stock_b_pos': 0,
        'stock_o_neg': 0,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Tiruvallur'},
    {   'beds_available': 25,
        'district': 'Chennai',
        'lat': 12.885562,
        'lng': 80.151595,
        'name': 'Government Health Center',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 0,
        'stock_o_pos': 10,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 17,
        'district': 'Coimbatore',
        'lat': 11.2385887,
        'lng': 76.9640887,
        'name': 'Government primary health center',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 2,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Coimbatore'},
    {   'beds_available': 23,
        'district': 'Coimbatore',
        'lat': 11.2376384,
        'lng': 76.9224629,
        'name': 'government sub health center',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 5,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 0,
        'stock_b_pos': 4,
        'stock_o_neg': 3,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Coimbatore'},
    {   'beds_available': 6,
        'district': 'Theni',
        'lat': 9.730261,
        'lng': 77.2802565,
        'name': 'cumbum government general hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 5,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 0,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Theni'},
    {   'beds_available': 16,
        'district': 'Tiruchirappalli',
        'lat': 10.815,
        'lng': 78.6576,
        'name': 'UPHC Ramalinga Nagar, UKT Malai',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 8,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Tiruchirappalli'},
    {   'beds_available': 15,
        'district': 'Virudhunagar',
        'lat': 9.2375269,
        'lng': 77.9070875,
        'name': 'Govt. Primary Hospital, Nalli',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 7,
        'stock_o_neg': 4,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Virudhunagar'},
    {   'beds_available': 18,
        'district': 'Kanyakumari',
        'lat': 8.2647152,
        'lng': 77.4439763,
        'name': 'Government Taluk Headquarters Hospital, Boothapandy',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Kanyakumari'},
    {   'beds_available': 15,
        'district': 'Madurai',
        'lat': 9.9350427,
        'lng': 78.1188461,
        'name': 'Sellur,Government Maternity Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Madurai'},
    {   'beds_available': 8,
        'district': 'Sivaganga',
        'lat': 10.110361,
        'lng': 78.5930852,
        'name': 'Government Maruthupandiyar Hospital, Tiruppathur',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 7,
        'stock_o_neg': 5,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Sivaganga'},
    {   'beds_available': 10,
        'district': 'Nagapattinam',
        'lat': 10.77246,
        'lng': 79.843971,
        'name': 'Nagapattinam Government District Head Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 8,
        'stock_o_neg': 2,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Nagapattinam'},
    {   'beds_available': 24,
        'district': 'Chennai',
        'lat': 13.2097678,
        'lng': 80.1121208,
        'name': 'Govt Hospital, Alamathi',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 8,
        'stock_o_neg': 5,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 24,
        'district': 'Dindigul',
        'lat': 10.308969,
        'lng': 77.6435935,
        'name': 'Thandikudi District Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 24,
        'district': 'Chennai',
        'lat': 13.07832,
        'lng': 80.243753,
        'name': 'Govt Kilpauk Medical College Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 2,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 1,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 21,
        'district': 'Chennai',
        'lat': 13.0991743,
        'lng': 80.2301988,
        'name': 'Government Maternity And Child Hospital',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 10,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 2,
        'stock_b_pos': 8,
        'stock_o_neg': 4,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 22,
        'district': 'Chennai',
        'lat': 13.10618,
        'lng': 80.286804,
        'name': 'Govt. Stanley Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 7,
        'stock_o_neg': 0,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 5,
        'district': 'Chennai',
        'lat': 13.1153048,
        'lng': 80.2233851,
        'name': 'Govt Peripheral Hospital Periyar Nagar',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 23,
        'district': 'Chennai',
        'lat': 13.1129012,
        'lng': 80.2957982,
        'name': 'Government Unani Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 5,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 12,
        'district': 'Chennai',
        'lat': 13.1142928,
        'lng': 80.2844517,
        'name': 'Chennai Corporation Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 0,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 21,
        'district': 'Thanjavur',
        'lat': 10.8581061,
        'lng': 79.2411564,
        'name': 'Govt, community Health Center, Melattur',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 2,
        'stock_o_neg': 3,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Thanjavur'},
    {   'beds_available': 22,
        'district': 'Tiruvarur',
        'lat': 10.87913,
        'lng': 79.611294,
        'name': 'Government General Taluk Hospital, Nannilam',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 3,
        'stock_b_pos': 0,
        'stock_o_neg': 5,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Tiruvarur'},
    {   'beds_available': 6,
        'district': 'Tiruchirappalli',
        'lat': 10.79729,
        'lng': 78.678497,
        'name': 'K. A. P. Viswanathan Government Medical College Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 4,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Tiruchirappalli'},
    {   'beds_available': 4,
        'district': 'Karur',
        'lat': 10.9615927,
        'lng': 78.080414,
        'name': 'Government Medical College Hospital, Karur',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 2,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Karur'},
    {   'beds_available': 6,
        'district': 'Vellore',
        'lat': 12.9156633,
        'lng': 79.1346498,
        'name': 'Government Pentland Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 2,
        'stock_b_pos': 2,
        'stock_o_neg': 1,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Vellore'},
    {   'beds_available': 11,
        'district': 'Ranipet',
        'lat': 12.9039497,
        'lng': 79.3333331,
        'name': 'Arcot Govt Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 7,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 0,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Ranipet'},
    {   'beds_available': 18,
        'district': 'Ariyalur',
        'lat': 11.1694117,
        'lng': 79.1495343,
        'name': 'Government General Hospital, Kadugur',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 4,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 4,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Ariyalur'},
    {   'beds_available': 12,
        'district': 'Salem',
        'lat': 11.7960034,
        'lng': 77.798885,
        'name': 'Mettur Govt Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 0,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Salem'},
    {   'beds_available': 10,
        'district': 'Cuddalore',
        'lat': 11.4902744,
        'lng': 79.7571092,
        'name': 'Government General Hospital Parangipettai',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 5,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Cuddalore'},
    {   'beds_available': 19,
        'district': 'Kallakurichi',
        'lat': 12.2259398,
        'lng': 79.0660738,
        'name': 'Government Tiruvannamalai Medical College and Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 10,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 6,
        'stock_o_neg': 1,
        'stock_o_pos': 6,
        'surgeon_on_duty': False,
        'village_area': 'Kallakurichi'},
    {   'beds_available': 5,
        'district': 'Chengalpattu',
        'lat': 12.35204,
        'lng': 80.002556,
        'name': 'Government General Hospital, Cheyyur',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 4,
        'stock_o_neg': 0,
        'stock_o_pos': 12,
        'surgeon_on_duty': False,
        'village_area': 'Chengalpattu'},
    {   'beds_available': 14,
        'district': 'Kallakurichi',
        'lat': 11.65429,
        'lng': 78.937592,
        'name': 'Govt. Hospital, Melur',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 8,
        'stock_o_neg': 1,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Kallakurichi'},
    {   'beds_available': 12,
        'district': 'Salem',
        'lat': 11.5683,
        'lng': 78.01211,
        'name': 'Vembadithalam Government General Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 5,
        'stock_o_neg': 1,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Salem'},
    {   'beds_available': 24,
        'district': 'Salem',
        'lat': 11.6660487,
        'lng': 78.1770681,
        'name': 'Ponnammapettai PHC',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 6,
        'stock_o_neg': 5,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Salem'},
    {   'beds_available': 11,
        'district': 'Erode',
        'lat': 11.33716,
        'lng': 77.727075,
        'name': 'Government Maternity Hospital, Agathiar',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 8,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 6,
        'surgeon_on_duty': False,
        'village_area': 'Erode'},
    {   'beds_available': 12,
        'district': 'Salem',
        'lat': 11.7048193,
        'lng': 78.2479415,
        'name': 'Valaisayur PHC',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 10,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 0,
        'stock_o_neg': 5,
        'stock_o_pos': 12,
        'surgeon_on_duty': False,
        'village_area': 'Salem'},
    {   'beds_available': 22,
        'district': 'Sivaganga',
        'lat': 9.840094,
        'lng': 78.485332,
        'name': 'Government District Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 7,
        'stock_o_neg': 4,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Sivaganga'},
    {   'beds_available': 22,
        'district': 'Sivaganga',
        'lat': 9.8387486,
        'lng': 78.4137465,
        'name': 'Pillur Government Primary Hospital',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 3,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Sivaganga'},
    {   'beds_available': 4,
        'district': 'Pudukkottai',
        'lat': 10.27924,
        'lng': 78.5317924,
        'name': 'Papaya Achchi Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 3,
        'stock_o_neg': 0,
        'stock_o_pos': 7,
        'surgeon_on_duty': True,
        'village_area': 'Pudukkottai'},
    {   'beds_available': 17,
        'district': 'Thanjavur',
        'lat': 10.76659,
        'lng': 79.071235,
        'name': 'Government Primary Hospital',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Thanjavur'},
    {   'beds_available': 25,
        'district': 'Ramanathapuram',
        'lat': 9.2871911,
        'lng': 79.3104069,
        'name': 'Government Malaria Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 1,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Ramanathapuram'},
    {   'beds_available': 19,
        'district': 'Thoothukudi',
        'lat': 8.9707417,
        'lng': 78.1853066,
        'name': 'Government Ayurvedha Hospital',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 5,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Thoothukudi'},
    {   'beds_available': 6,
        'district': 'Virudhunagar',
        'lat': 9.4590865,
        'lng': 77.5551908,
        'name': 'RJPM Govt Maternity & Health Care Centre',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 3,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 0,
        'stock_o_neg': 5,
        'stock_o_pos': 10,
        'surgeon_on_duty': True,
        'village_area': 'Virudhunagar'},
    {   'beds_available': 16,
        'district': 'Tiruchirappalli',
        'lat': 10.8127985,
        'lng': 78.6345428,
        'name': 'Government Sidha Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 4,
        'stock_o_neg': 1,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Tiruchirappalli'},
    {   'beds_available': 17,
        'district': 'Theni',
        'lat': 9.731135,
        'lng': 77.280955,
        'name': 'Government General Hospital',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 1,
        'stock_o_neg': 3,
        'stock_o_pos': 2,
        'surgeon_on_duty': False,
        'village_area': 'Theni'},
    {   'beds_available': 12,
        'district': 'Sivaganga',
        'lat': 9.9407414,
        'lng': 78.8255999,
        'name': 'Devakottai Urban PHC',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 5,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Sivaganga'},
    {   'beds_available': 21,
        'district': 'Chennai',
        'lat': 13.0808972,
        'lng': 80.2773284,
        'name': 'Rajiv Gandhi Government General Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 4,
        'stock_ab_neg': 2,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 0,
        'stock_o_neg': 4,
        'stock_o_pos': 7,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 20,
        'district': 'Erode',
        'lat': 11.3393048,
        'lng': 77.717926,
        'name': 'District Hospital, Eroda',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 7,
        'stock_o_neg': 2,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Erode'},
    {   'beds_available': 24,
        'district': 'Thanjavur',
        'lat': 10.7844153,
        'lng': 79.1362994,
        'name': 'Government Raja Mirasdar Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 2,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Thanjavur'},
    {   'beds_available': 12,
        'district': 'Madurai',
        'lat': 9.9271051,
        'lng': 78.1301681,
        'name': 'Government Rajaji Hospital in Madurai',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Madurai'},
    {   'beds_available': 25,
        'district': 'Chennai',
        'lat': 13.034006,
        'lng': 80.2078405,
        'name': 'Govt Peripheral Hospital KK Nagar',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 5,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 2,
        'stock_o_neg': 2,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 7,
        'district': 'Chennai',
        'lat': 13.1090673,
        'lng': 80.288719,
        'name': 'Government Rsrm Lying Hospital',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 3,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 12,
        'district': 'Chennai',
        'lat': 13.1260276,
        'lng': 80.2866925,
        'name': 'Government Peripheral Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 3,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 17,
        'district': 'Chennai',
        'lat': 13.0693752,
        'lng': 80.2741496,
        'name': 'Tamil Nadu Government Multi Super Speciality Hospital',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 5,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 7,
        'district': 'Dindigul',
        'lat': 10.3530399,
        'lng': 78.0902637,
        'name': 'Siluvathur PHC',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 2,
        'stock_b_pos': 8,
        'stock_o_neg': 3,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Dindigul'},
    {   'beds_available': 24,
        'district': 'Dindigul',
        'lat': 10.3606804,
        'lng': 77.973788,
        'name': 'Kamala Nehru Urban Primary Health Centre',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 18,
        'district': 'Pudukkottai',
        'lat': 10.4101898,
        'lng': 78.8481628,
        'name': 'Government Medical College & Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 2,
        'stock_b_pos': 6,
        'stock_o_neg': 2,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Pudukkottai'},
    {   'beds_available': 18,
        'district': 'Tiruvarur',
        'lat': 10.5927913,
        'lng': 79.4163552,
        'name': 'Govt Dispenssry and School',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 7,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 5,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Tiruvarur'},
    {   'beds_available': 13,
        'district': 'Sivaganga',
        'lat': 9.838807,
        'lng': 78.4782631,
        'name': 'Government Sivagangai Medical College & Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 10,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 2,
        'stock_o_neg': 0,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Sivaganga'},
    {   'beds_available': 22,
        'district': 'Pudukkottai',
        'lat': 10.0638576,
        'lng': 78.7771791,
        'name': 'Government Hospiral',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 5,
        'stock_o_neg': 2,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Pudukkottai'},
    {   'beds_available': 10,
        'district': 'Coimbatore',
        'lat': 10.8800121,
        'lng': 76.9247754,
        'name': 'T.M.Palayam PHC',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 3,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Coimbatore'},
    {   'beds_available': 18,
        'district': 'Thanjavur',
        'lat': 10.8581073,
        'lng': 79.2411464,
        'name': 'Govt.Community Health Center, melattur',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 12,
        'surgeon_on_duty': True,
        'village_area': 'Thanjavur'},
    {   'beds_available': 10,
        'district': 'Madurai',
        'lat': 9.9250034,
        'lng': 78.1374473,
        'name': 'Govt Rajaji Hospital Emergency Ward',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Madurai'},
    {   'beds_available': 8,
        'district': 'Thoothukudi',
        'lat': 8.7981499,
        'lng': 78.1360638,
        'name': 'Thoothukudi Government Medical College Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 2,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Thoothukudi'},
    {   'beds_available': 4,
        'district': 'Dindigul',
        'lat': 10.3644811,
        'lng': 77.9764388,
        'name': 'Government Medical College Hospital, Dindigul',
        'nicu_beds_available': 0,
        'state': 'Tamil Nadu',
        'stock_a_neg': 4,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 1,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 23,
        'district': 'Pudukkottai',
        'lat': 10.1038513,
        'lng': 78.7611232,
        'name': 'Government District Headquarters Hospital',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 5,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 4,
        'stock_o_pos': 6,
        'surgeon_on_duty': False,
        'village_area': 'Pudukkottai'},
    {   'beds_available': 24,
        'district': 'Dindigul',
        'lat': 10.3618726,
        'lng': 77.9869216,
        'name': 'Government Siddha hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 2,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 0,
        'stock_o_neg': 4,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 11,
        'district': 'Dindigul',
        'lat': 10.34989,
        'lng': 77.9860667,
        'name': 'Mariyanathapuram PHC',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 2,
        'stock_b_pos': 1,
        'stock_o_neg': 4,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 10,
        'district': 'Tirunelveli',
        'lat': 8.7246574,
        'lng': 77.7326837,
        'name': 'Government Siddha Medical College and Hospital',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Tirunelveli'},
    {   'beds_available': 22,
        'district': 'Salem',
        'lat': 11.7959119,
        'lng': 77.7987959,
        'name': 'Govt Hospital Mettur',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 2,
        'stock_a_pos': 5,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Salem'},
    {   'beds_available': 9,
        'district': 'Kanyakumari',
        'lat': 8.1158029,
        'lng': 77.3803867,
        'name': 'Rajakkamangalam PHC',
        'nicu_beds_available': 1,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 7,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 0,
        'stock_o_neg': 3,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Kanyakumari'},
    {   'beds_available': 11,
        'district': 'Ranipet',
        'lat': 12.9916638,
        'lng': 79.2547376,
        'name': 'Government Primary Healthcare Centre',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 10,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 6,
        'stock_o_neg': 0,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Ranipet'},
    {   'beds_available': 4,
        'district': 'Theni',
        'lat': 10.2402835,
        'lng': 77.5023222,
        'name': 'UPHC, Kodaikanal',
        'nicu_beds_available': 3,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 0,
        'stock_o_pos': 2,
        'surgeon_on_duty': False,
        'village_area': 'Theni'},
    {   'beds_available': 16,
        'district': 'Chennai',
        'lat': 13.0765495,
        'lng': 80.2245565,
        'name': 'Government child birth Hospital',
        'nicu_beds_available': 2,
        'state': 'Tamil Nadu',
        'stock_a_neg': 0,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 6,
        'stock_o_neg': 5,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Chennai'},
    {   'beds_available': 6,
        'district': 'Chengalpattu',
        'lat': 12.7912032,
        'lng': 80.0329076,
        'name': 'Government Primary Health Centre',
        'nicu_beds_available': 4,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 1,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Chengalpattu'},
    {   'beds_available': 6,
        'district': 'Chennai',
        'lat': 13.0766394,
        'lng': 80.2430155,
        'name': 'Govt. Kilpauk Hospital',
        'nicu_beds_available': 5,
        'state': 'Tamil Nadu',
        'stock_a_neg': 3,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 5,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Chennai'},
    {   'beds_available': 10,
        'district': 'Dindigul',
        'lat': 10.3329349,
        'lng': 77.9827453,
        'name': 'Government Medical College - Dindigul',
        'nicu_beds_available': 6,
        'state': 'Tamil Nadu',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 5,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Dindigul'},
    {   'beds_available': 11,
        'district': 'Nagpur',
        'lat': 21.1295149,
        'lng': 79.0974689,
        'name': 'Govt. Medical College',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 1,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Nagpur'},
    {   'beds_available': 9,
        'district': 'Mumbai Suburban',
        'lat': 19.1597156,
        'lng': 72.8399209,
        'name': 'Siddarth Municipal Hospital',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 10,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 1,
        'surgeon_on_duty': True,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 19,
        'district': 'Aurangabad',
        'lat': 19.8918831,
        'lng': 75.3594412,
        'name': 'municipal hospital for women & child',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 4,
        'stock_o_neg': 4,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Aurangabad'},
    {   'beds_available': 22,
        'district': 'Nagpur',
        'lat': 21.1703616,
        'lng': 79.064192,
        'name': 'Central Govt Heath Scheme(CGHS) Clinic',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 1,
        'stock_o_neg': 4,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Nagpur'},
    {   'beds_available': 12,
        'district': 'Mumbai Suburban',
        'lat': 19.2007076,
        'lng': 72.8221715,
        'name': 'Government General Hospital, Malwani Malad',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 0,
        'stock_b_pos': 7,
        'stock_o_neg': 1,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 20,
        'district': 'Mumbai Suburban',
        'lat': 19.0815079,
        'lng': 72.8831157,
        'name': 'Kurla Municipal Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 10,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 5,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 21,
        'district': 'Pune',
        'lat': 18.1439124,
        'lng': 73.8520056,
        'name': 'Sub District Hospital Bhor',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 7,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 7,
        'stock_o_neg': 1,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Pune'},
    {   'beds_available': 15,
        'district': 'Solapur',
        'lat': 18.1206808,
        'lng': 75.0258983,
        'name': 'Sub District Hospital, Indapur',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 1,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 2,
        'stock_b_pos': 0,
        'stock_o_neg': 2,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Solapur'},
    {   'beds_available': 14,
        'district': 'Solapur',
        'lat': 17.6377251,
        'lng': 75.9046376,
        'name': 'Wachche Hospital, Solapur',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 2,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Solapur'},
    {   'beds_available': 6,
        'district': 'Solapur',
        'lat': 17.685862,
        'lng': 75.3331795,
        'name': 'Sub District Hospital, Pandharpur',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 1,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Solapur'},
    {   'beds_available': 9,
        'district': 'Nanded',
        'lat': 18.545425,
        'lng': 77.5844353,
        'name': 'Sub District Hospital, Degloor',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 1,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 1,
        'surgeon_on_duty': False,
        'village_area': 'Nanded'},
    {   'beds_available': 18,
        'district': 'Beed',
        'lat': 18.9869163,
        'lng': 75.7533207,
        'name': 'District Hospital,Beed',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 6,
        'stock_o_neg': 4,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Beed'},
    {   'beds_available': 17,
        'district': 'Satara',
        'lat': 17.6913198,
        'lng': 74.0094374,
        'name': 'District Hospital, Satara',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 4,
        'stock_o_pos': 10,
        'surgeon_on_duty': True,
        'village_area': 'Satara'},
    {   'beds_available': 6,
        'district': 'Thane',
        'lat': 19.2314914,
        'lng': 73.1368687,
        'name': 'KDMC Kolsewadi Municipal Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 10,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 6,
        'surgeon_on_duty': False,
        'village_area': 'Thane'},
    {   'beds_available': 18,
        'district': 'Ahmednagar',
        'lat': 19.108436,
        'lng': 74.735394,
        'name': 'District Hospital, Ahmednagar',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Ahmednagar'},
    {   'beds_available': 14,
        'district': 'Nanded',
        'lat': 19.143427,
        'lng': 77.324738,
        'name': 'NDMC Arabgalli Municipal Hospital',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 8,
        'stock_o_neg': 1,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Nanded'},
    {   'beds_available': 12,
        'district': 'Nanded',
        'lat': 19.156482,
        'lng': 77.313095,
        'name': 'Dr Shankarrao Chavan Government Medical College and Hospital, Vazirabad',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 6,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 0,
        'stock_o_neg': 3,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Nanded'},
    {   'beds_available': 15,
        'district': 'Satara',
        'lat': 17.288161,
        'lng': 74.186186,
        'name': 'Sub-District Hospital Karad',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 1,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Satara'},
    {   'beds_available': 5,
        'district': 'Satara',
        'lat': 17.9919639,
        'lng': 74.4346258,
        'name': 'Sub-District Hospital Phaltan',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 10,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 0,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Satara'},
    {   'beds_available': 15,
        'district': 'Raigad',
        'lat': 18.4342863,
        'lng': 73.1181287,
        'name': 'Roha, Sub District Hospital',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 10,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Raigad'},
    {   'beds_available': 24,
        'district': 'Raigad',
        'lat': 18.0498631,
        'lng': 73.0174109,
        'name': 'Shrivardhan, Sub District Hospital',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 0,
        'stock_o_pos': 12,
        'surgeon_on_duty': False,
        'village_area': 'Raigad'},
    {   'beds_available': 21,
        'district': 'Beed',
        'lat': 19.263871,
        'lng': 75.75079,
        'name': 'Sub-District Hospital Georai',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 9,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 5,
        'stock_o_neg': 4,
        'stock_o_pos': 0,
        'surgeon_on_duty': False,
        'village_area': 'Beed'},
    {   'beds_available': 22,
        'district': 'Aurangabad',
        'lat': 19.697402,
        'lng': 75.008919,
        'name': 'Sub-District Hospital Gangapur',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 10,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 3,
        'stock_o_pos': 6,
        'surgeon_on_duty': False,
        'village_area': 'Aurangabad'},
    {   'beds_available': 19,
        'district': 'Parbhani',
        'lat': 19.2713708,
        'lng': 76.7644813,
        'name': 'District Hospital Parbhani',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 1,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 5,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Parbhani'},
    {   'beds_available': 21,
        'district': 'Palghar',
        'lat': 19.4498063,
        'lng': 72.8181478,
        'name': 'UPHC Ranale Talao',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 0,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Palghar'},
    {   'beds_available': 20,
        'district': 'Sangli',
        'lat': 16.859925,
        'lng': 74.552072,
        'name': 'Sangalwadi Municipal Hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 7,
        'stock_o_neg': 0,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Sangli'},
    {   'beds_available': 7,
        'district': 'Sangli',
        'lat': 16.837153,
        'lng': 74.647081,
        'name': 'Government Medical College And Hospital Miraj',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 3,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 6,
        'stock_o_neg': 2,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Sangli'},
    {   'beds_available': 5,
        'district': 'Latur',
        'lat': 18.849645,
        'lng': 76.5327379,
        'name': 'SUB-District Hospital Parli',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 3,
        'stock_o_neg': 4,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Latur'},
    {   'beds_available': 11,
        'district': 'Beed',
        'lat': 18.713928,
        'lng': 76.089605,
        'name': 'Sub-District Hospital Kaij',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 8,
        'stock_o_neg': 0,
        'stock_o_pos': 12,
        'surgeon_on_duty': True,
        'village_area': 'Beed'},
    {   'beds_available': 18,
        'district': 'Nanded',
        'lat': 18.5624038,
        'lng': 77.4551005,
        'name': 'Govt. Hospital, Rajura Bk.',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 3,
        'stock_b_pos': 8,
        'stock_o_neg': 5,
        'stock_o_pos': 7,
        'surgeon_on_duty': True,
        'village_area': 'Nanded'},
    {   'beds_available': 18,
        'district': 'Buldhana',
        'lat': 20.8843497,
        'lng': 76.2035114,
        'name': 'Sub-District Hospital, Malkapur',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 4,
        'stock_o_pos': 0,
        'surgeon_on_duty': False,
        'village_area': 'Buldhana'},
    {   'beds_available': 6,
        'district': 'Dhule',
        'lat': 20.9016416,
        'lng': 74.7711279,
        'name': 'District Hospital, Dhule',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 2,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Dhule'},
    {   'beds_available': 19,
        'district': 'Bhandara',
        'lat': 21.0862493,
        'lng': 79.9881813,
        'name': 'Sub District Hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 3,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 6,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Bhandara'},
    {   'beds_available': 12,
        'district': 'Amravati',
        'lat': 20.9935702,
        'lng': 78.2279469,
        'name': 'Sub-District Hospital Arvi',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 3,
        'stock_o_pos': 2,
        'surgeon_on_duty': False,
        'village_area': 'Amravati'},
    {   'beds_available': 12,
        'district': 'Nagpur',
        'lat': 21.15405,
        'lng': 79.094649,
        'name': 'Indira Gandhi Government Medical College and Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 2,
        'stock_o_neg': 2,
        'stock_o_pos': 2,
        'surgeon_on_duty': False,
        'village_area': 'Nagpur'},
    {   'beds_available': 22,
        'district': 'Akola',
        'lat': 20.7026029,
        'lng': 77.0019289,
        'name': 'Govt. Medical College and Hospital',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 5,
        'stock_o_pos': 8,
        'surgeon_on_duty': True,
        'village_area': 'Akola'},
    {   'beds_available': 11,
        'district': 'Amravati',
        'lat': 21.3393182,
        'lng': 78.0106932,
        'name': 'Sub District Hospital, Morshi',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 2,
        'stock_b_pos': 8,
        'stock_o_neg': 2,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Amravati'},
    {   'beds_available': 17,
        'district': 'Dhule',
        'lat': 21.355138,
        'lng': 74.883669,
        'name': 'Shirpur Sub District Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 8,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 0,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Dhule'},
    {   'beds_available': 22,
        'district': 'Bhandara',
        'lat': 21.382449,
        'lng': 79.745473,
        'name': 'Sub-District Hospital Tumsar',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 2,
        'stock_o_pos': 12,
        'surgeon_on_duty': True,
        'village_area': 'Bhandara'},
    {   'beds_available': 5,
        'district': 'Buldhana',
        'lat': 20.532784,
        'lng': 76.186566,
        'name': 'District Hospital, Buldana',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 4,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 2,
        'stock_b_pos': 1,
        'stock_o_neg': 3,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Buldhana'},
    {   'beds_available': 10,
        'district': 'Chandrapur',
        'lat': 20.4971981,
        'lng': 79.3609591,
        'name': 'Sub District Hospital, Chimur',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 1,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Chandrapur'},
    {   'beds_available': 20,
        'district': 'Akola',
        'lat': 20.4859395,
        'lng': 77.4803659,
        'name': 'Sub-District Hospital, Karanja',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 4,
        'stock_ab_neg': 1,
        'stock_ab_pos': 3,
        'stock_b_neg': 2,
        'stock_b_pos': 5,
        'stock_o_neg': 0,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Akola'},
    {   'beds_available': 15,
        'district': 'Nashik',
        'lat': 19.845534,
        'lng': 73.9997151,
        'name': 'Sinnar Municipal Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 3,
        'stock_o_pos': 4,
        'surgeon_on_duty': False,
        'village_area': 'Nashik'},
    {   'beds_available': 6,
        'district': 'Jalna',
        'lat': 19.83228,
        'lng': 75.874466,
        'name': 'District Hospital, Jalna',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 1,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 4,
        'stock_o_pos': 12,
        'surgeon_on_duty': True,
        'village_area': 'Jalna'},
    {   'beds_available': 13,
        'district': 'Jalna',
        'lat': 20.3010738,
        'lng': 75.6494794,
        'name': 'Sub-District Hospital, Sillod',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 3,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 0,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Jalna'},
    {   'beds_available': 15,
        'district': 'Aurangabad',
        'lat': 19.924128,
        'lng': 74.727928,
        'name': 'Sub-District Hospital, Vaijapur',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 9,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 11,
        'surgeon_on_duty': False,
        'village_area': 'Aurangabad'},
    {   'beds_available': 9,
        'district': 'Akola',
        'lat': 20.7018883,
        'lng': 77.0002905,
        'name': 'Government Medical College & Multispeciality Hospital',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 7,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 7,
        'stock_o_neg': 0,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Akola'},
    {   'beds_available': 23,
        'district': 'Nagpur',
        'lat': 21.1727983,
        'lng': 79.0914599,
        'name': 'Jamshed Ji Tata Municipal Hospital',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 1,
        'stock_o_pos': 12,
        'surgeon_on_duty': False,
        'village_area': 'Nagpur'},
    {   'beds_available': 8,
        'district': 'Amravati',
        'lat': 20.9365458,
        'lng': 77.7499787,
        'name': 'Masanganj Municipal Hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 1,
        'stock_ab_neg': 0,
        'stock_ab_pos': 2,
        'stock_b_neg': 0,
        'stock_b_pos': 1,
        'stock_o_neg': 5,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Amravati'},
    {   'beds_available': 14,
        'district': 'Osmanabad',
        'lat': 18.141394,
        'lng': 75.733874,
        'name': 'Government Sub Hospital',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 5,
        'stock_o_pos': 0,
        'surgeon_on_duty': False,
        'village_area': 'Osmanabad'},
    {   'beds_available': 18,
        'district': 'Sangli',
        'lat': 17.0603756,
        'lng': 74.8630135,
        'name': 'Government Civil Hospital',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 0,
        'stock_ab_neg': 2,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 5,
        'stock_o_neg': 3,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Sangli'},
    {   'beds_available': 4,
        'district': 'Beed',
        'lat': 19.0647304,
        'lng': 75.4189126,
        'name': 'Shirur Government Civil Hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 4,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 4,
        'stock_o_pos': 10,
        'surgeon_on_duty': False,
        'village_area': 'Beed'},
    {   'beds_available': 18,
        'district': 'Thane',
        'lat': 19.3402602,
        'lng': 72.8039102,
        'name': 'New Municipal Hospital',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 2,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 0,
        'stock_b_pos': 3,
        'stock_o_neg': 1,
        'stock_o_pos': 7,
        'surgeon_on_duty': True,
        'village_area': 'Thane'},
    {   'beds_available': 22,
        'district': 'Mumbai Suburban',
        'lat': 18.982756,
        'lng': 73.107745,
        'name': 'Government Rural Hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 9,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 5,
        'stock_o_pos': 12,
        'surgeon_on_duty': False,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 16,
        'district': 'Mumbai Suburban',
        'lat': 19.097922,
        'lng': 72.892138,
        'name': 'Mohili Village Municipal Hospital',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 0,
        'stock_o_neg': 5,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 25,
        'district': 'Dhule',
        'lat': 20.8650627,
        'lng': 74.7629432,
        'name': 'Shri.Bhausaheb Hire Govt.Medical College',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 4,
        'stock_o_neg': 4,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Dhule'},
    {   'beds_available': 24,
        'district': 'Wardha',
        'lat': 20.7318289,
        'lng': 78.6096637,
        'name': 'Pulfail UPHC A',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 4,
        'stock_o_neg': 5,
        'stock_o_pos': 7,
        'surgeon_on_duty': False,
        'village_area': 'Wardha'},
    {   'beds_available': 13,
        'district': 'Pune',
        'lat': 18.5799148,
        'lng': 73.9827951,
        'name': 'PHC',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 0,
        'stock_b_pos': 7,
        'stock_o_neg': 1,
        'stock_o_pos': 3,
        'surgeon_on_duty': True,
        'village_area': 'Pune'},
    {   'beds_available': 16,
        'district': 'Pune',
        'lat': 18.7636501,
        'lng': 73.5552679,
        'name': 'PHC Khadkala',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 6,
        'stock_ab_neg': 0,
        'stock_ab_pos': 4,
        'stock_b_neg': 2,
        'stock_b_pos': 1,
        'stock_o_neg': 2,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Pune'},
    {   'beds_available': 22,
        'district': 'Nagpur',
        'lat': 21.3061567,
        'lng': 78.9184588,
        'name': 'Primary Health Center PHC Dhapewada',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 4,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 3,
        'stock_o_neg': 4,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Nagpur'},
    {   'beds_available': 8,
        'district': 'Satara',
        'lat': 17.5982016,
        'lng': 73.8728339,
        'name': 'Primary Health Centre',
        'nicu_beds_available': 2,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 0,
        'stock_ab_neg': 0,
        'stock_ab_pos': 1,
        'stock_b_neg': 2,
        'stock_b_pos': 7,
        'stock_o_neg': 2,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Satara'},
    {   'beds_available': 22,
        'district': 'Aurangabad',
        'lat': 19.8907866,
        'lng': 75.319315,
        'name': 'Govt Medical College & Hospital',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 2,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 2,
        'stock_b_pos': 1,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Aurangabad'},
    {   'beds_available': 10,
        'district': 'Satara',
        'lat': 18.1519568,
        'lng': 74.5753117,
        'name': 'Silver Jubilee Sub District Hospital, Baramati',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 2,
        'stock_b_pos': 7,
        'stock_o_neg': 4,
        'stock_o_pos': 6,
        'surgeon_on_duty': True,
        'village_area': 'Satara'},
    {   'beds_available': 24,
        'district': 'Hingoli',
        'lat': 19.8430188,
        'lng': 76.6578221,
        'name': 'PHC, Kapadsingi',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 8,
        'stock_ab_neg': 0,
        'stock_ab_pos': 3,
        'stock_b_neg': 0,
        'stock_b_pos': 7,
        'stock_o_neg': 0,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Hingoli'},
    {   'beds_available': 11,
        'district': 'Thane',
        'lat': 19.5822702,
        'lng': 73.3909098,
        'name': 'Dr.Astin Hospital & Government Office',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 7,
        'stock_o_neg': 3,
        'stock_o_pos': 5,
        'surgeon_on_duty': True,
        'village_area': 'Thane'},
    {   'beds_available': 18,
        'district': 'Kolhapur',
        'lat': 16.6700385,
        'lng': 74.234857,
        'name': 'Rajarshi Chhatrapati Shahu Maharaj Government Medical college and CPR hospital',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 7,
        'stock_o_neg': 3,
        'stock_o_pos': 1,
        'surgeon_on_duty': False,
        'village_area': 'Kolhapur'},
    {   'beds_available': 18,
        'district': 'Raigad',
        'lat': 18.2357833,
        'lng': 73.2816687,
        'name': 'Sub District Hospital, Mangaon',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 0,
        'stock_o_neg': 0,
        'stock_o_pos': 1,
        'surgeon_on_duty': False,
        'village_area': 'Raigad'},
    {   'beds_available': 24,
        'district': 'Mumbai Suburban',
        'lat': 19.1409344,
        'lng': 72.8536704,
        'name': 'Hindu Hruday Samrat Balasaheb Thackerey Trauma Care Municipal Hospital',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 3,
        'stock_b_pos': 1,
        'stock_o_neg': 3,
        'stock_o_pos': 10,
        'surgeon_on_duty': True,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 23,
        'district': 'Hingoli',
        'lat': 19.7221417,
        'lng': 77.15437,
        'name': 'Government Civil Hospital, Hingoli',
        'nicu_beds_available': 5,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 9,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 8,
        'stock_o_neg': 5,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Hingoli'},
    {   'beds_available': 6,
        'district': 'Chandrapur',
        'lat': 20.2344277,
        'lng': 79.0031638,
        'name': 'Sub-District Hospital',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 0,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 6,
        'stock_o_neg': 3,
        'stock_o_pos': 2,
        'surgeon_on_duty': True,
        'village_area': 'Chandrapur'},
    {   'beds_available': 18,
        'district': 'Latur',
        'lat': 18.3360819,
        'lng': 76.8164,
        'name': 'Shirur Anantpal PHC',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 4,
        'stock_b_neg': 0,
        'stock_b_pos': 6,
        'stock_o_neg': 5,
        'stock_o_pos': 1,
        'surgeon_on_duty': False,
        'village_area': 'Latur'},
    {   'beds_available': 4,
        'district': 'Ratnagiri',
        'lat': 16.9884007,
        'lng': 73.2992631,
        'name': 'District Hospital, Ratnagiri',
        'nicu_beds_available': 3,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 2,
        'stock_b_pos': 4,
        'stock_o_neg': 0,
        'stock_o_pos': 0,
        'surgeon_on_duty': True,
        'village_area': 'Ratnagiri'},
    {   'beds_available': 20,
        'district': 'Latur',
        'lat': 18.3906989,
        'lng': 77.1178142,
        'name': 'Sub District Hospital, Udgir',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 1,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 0,
        'stock_o_neg': 4,
        'stock_o_pos': 8,
        'surgeon_on_duty': False,
        'village_area': 'Latur'},
    {   'beds_available': 6,
        'district': 'Sindhudurg',
        'lat': 16.116248,
        'lng': 73.6900576,
        'name': 'District Hospital Sindhudurg',
        'nicu_beds_available': 1,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 10,
        'stock_ab_neg': 0,
        'stock_ab_pos': 5,
        'stock_b_neg': 1,
        'stock_b_pos': 6,
        'stock_o_neg': 4,
        'stock_o_pos': 9,
        'surgeon_on_duty': True,
        'village_area': 'Sindhudurg'},
    {   'beds_available': 9,
        'district': 'Nanded',
        'lat': 19.3252193,
        'lng': 77.1568389,
        'name': 'Sub District Hospital Basmath',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 9,
        'stock_ab_neg': 1,
        'stock_ab_pos': 0,
        'stock_b_neg': 3,
        'stock_b_pos': 3,
        'stock_o_neg': 2,
        'stock_o_pos': 9,
        'surgeon_on_duty': False,
        'village_area': 'Nanded'},
    {   'beds_available': 6,
        'district': 'Yavatmal',
        'lat': 20.0101411,
        'lng': 78.5476424,
        'name': 'Sub-District Hospital Pandharkawada',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 5,
        'stock_ab_neg': 2,
        'stock_ab_pos': 0,
        'stock_b_neg': 1,
        'stock_b_pos': 2,
        'stock_o_neg': 2,
        'stock_o_pos': 4,
        'surgeon_on_duty': True,
        'village_area': 'Yavatmal'},
    {   'beds_available': 11,
        'district': 'Latur',
        'lat': 18.4521142,
        'lng': 76.6748662,
        'name': 'PHC Bhatangli',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 6,
        'stock_ab_neg': 1,
        'stock_ab_pos': 2,
        'stock_b_neg': 1,
        'stock_b_pos': 1,
        'stock_o_neg': 2,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Latur'},
    {   'beds_available': 8,
        'district': 'Mumbai Suburban',
        'lat': 19.1854369,
        'lng': 72.819154,
        'name': 'Government Hospita',
        'nicu_beds_available': 0,
        'state': 'Maharashtra',
        'stock_a_neg': 3,
        'stock_a_pos': 2,
        'stock_ab_neg': 1,
        'stock_ab_pos': 1,
        'stock_b_neg': 1,
        'stock_b_pos': 4,
        'stock_o_neg': 2,
        'stock_o_pos': 3,
        'surgeon_on_duty': False,
        'village_area': 'Mumbai Suburban'},
    {   'beds_available': 6,
        'district': 'Nagpur',
        'lat': 21.4578189,
        'lng': 79.1695998,
        'name': 'govt veternity hospital',
        'nicu_beds_available': 4,
        'state': 'Maharashtra',
        'stock_a_neg': 4,
        'stock_a_pos': 7,
        'stock_ab_neg': 1,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 2,
        'stock_o_neg': 4,
        'stock_o_pos': 5,
        'surgeon_on_duty': False,
        'village_area': 'Nagpur'},
    {   'beds_available': 25,
        'district': 'Ratnagiri',
        'lat': 17.5547288,
        'lng': 73.154013,
        'name': 'Anjanvel PHC',
        'nicu_beds_available': 6,
        'state': 'Maharashtra',
        'stock_a_neg': 0,
        'stock_a_pos': 8,
        'stock_ab_neg': 2,
        'stock_ab_pos': 5,
        'stock_b_neg': 3,
        'stock_b_pos': 5,
        'stock_o_neg': 3,
        'stock_o_pos': 11,
        'surgeon_on_duty': True,
        'village_area': 'Ratnagiri'}]


def seed():
    init_db()
    db = SessionLocal()
    try:
        existing = db.query(Hospital).count()
        if existing > 0:
            print(f"Clearing {existing} existing hospital records...")
            db.query(Hospital).delete()
            db.commit()

        for h in HOSPITALS:
            db.add(Hospital(**h))
        db.commit()

        print(f"Seeded {len(HOSPITALS)} hospitals across Tamil Nadu and Maharashtra.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
