/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "var(--color-background, #f6fafe)",
        "surface": "var(--color-surface, #ffffff)",
        "surface-bright": "#f6fafe",
        "surface-dim": "#d6dade",
        "surface-variant": "#dfe3e7",
        "surface-border": "#e2e8f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f8",
        "surface-container": "#eaeef2",
        "surface-container-high": "#e4e9ed",
        "surface-container-highest": "#dfe3e7",
        "primary": "#091426",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "on-primary-container": "#8590a6",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "secondary": "#006b5f",
        "secondary-container": "#62fae3",
        "secondary-fixed": "#62fae3",
        "secondary-fixed-dim": "#3cddc7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007165",
        "teal-accent": "#2dd4bf",
        "medical-blue-muted": "#1e293b",
        "on-surface": "#171c1f",
        "on-surface-variant": "#45464d",
        "on-background": "#171c1f",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "status-success": "#22c55e",
        "status-critical": "#ef4444",
        "status-warning": "#f59e0b",
        "status-info": "#3b82f6",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
      },
      spacing: {
        "margin-page": "2rem",
        "margin-mobile": "1rem",
        "sidebar-width": "280px",
        "gutter-grid": "1.5rem",
        "card-padding": "1.25rem",
        "stack-gap": "1rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "max-width": "1280px",
      }
    },
  },
  plugins: [],
}
