import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    analytics: "Regional Analytics & Heatmap",
    admin_governance: "Admin & Governance",
    maternal_analytics_tab: "Maternal Health Analytics",
    pediatric_analytics_tab: "Pediatric & Neonatal Analytics",
    live_epidemiology: "LIVE EPIDEMIOLOGY",
    master_controls: "MASTER CONTROLS",
    time_24h: "24 HOURS",
    time_7d: "7 DAYS",
    time_30d: "30 DAYS",
    time_ytd: "YTD",
    maternal_screenings: "MATERNAL SCREENINGS",
    pediatric_screenings: "PEDIATRIC SCREENINGS",
    avg_time_to_care: "AVERAGE TIME-TO-CARE",
    ml_prediction_accuracy: "ML PREDICTION ACCURACY",
    district_risk_stratification: "District Risk Stratification & ICU Stress Index",
    district_pediatric_stratification: "District Pediatric Risk & NICU Stress Index",
    primary_maternal_risk_drivers: "Primary Maternal Risk Drivers",
    primary_pediatric_risk_drivers: "Primary Pediatric Risk Drivers",
    recent_case_outcomes: "Recent High-Risk Case Outcomes & Transfer Efficacy",
    recent_peds_outcomes: "Recent Pediatric Emergency Transfers & SNCU Outcomes",
    gateway_uptime: "GATEWAY UPTIME",
    ml_latency: "ML INFERENCE LATENCY",
    active_websockets: "ACTIVE WEBSOCKETS",
    emergency_queue: "EMERGENCY ROUTING QUEUE",
    tab_audit_trail: "Master Audit Trail",
    tab_regional_governance: "Regional Routing Governance",
    tab_clinician_roles: "Clinicians & Access Roles",
    btn_export_audit: "Export Audit Logs",
    btn_broadcast_alert: "Broadcast Alert",
    filter_severity: "Filter by Severity",
    all_divisions: "All Divisions",
    case_id: "CASE ID",
    receiving_facility: "RECEIVING FACILITY",
    time_to_care: "TIME TO CARE",
    clinical_outcome: "CLINICAL OUTCOME",

    dashboard: "Command Center",
    hospitals: "Hospitals Directory",
    maternal_portal: "Maternal Portal",
    child_portal: "Pediatric VIPER",
    chronic_portal: "Cardio / NCD Portal",
    live_gis_matrix: "Live Regional Medical GIS Matrix",
    asha_agents: "ASHA Agents",
    active_fleet: "108 Active Fleet",
    routing_dispatch: "Routing Intelligence & Dispatch",
    starting_point: "1. STARTING POINT",
    home_address: "Home / Address",
    live_gps_device: "Live GPS Device Location",
    dest_hospital: "2. DESTINATION HOSPITAL",
    auto_selected_nearest: "Auto-selected nearest",
    optimal_referral: "OPTIMAL REFERRAL",
    standby_receiving: "STANDBY RECEIVING",
    dispatch_ambulance: "Dispatch 108 Ambulance",
    filters_label: "FILTERS",
    // Nav & Brand
    app_title: "MaatriMarg",
    tagline: "National Maternal & Emergency Care AI Network",
    national_command: "National Command Infrastructure Active • Maharashtra & Tamil Nadu",
    home_sos_route: "Home SOS Route (Google Maps)",
    clinician_login_btn: "Clinician Login",
    dho_hq: "DHO Command HQ",

    // Landing Page
    hero_headline_1: "Maternal Healthcare",
    hero_headline_2: "Intelligence Platform",
    hero_subtitle: "Predict clinical risk. Optimize real-time ICU bed allocation. Seamlessly route mothers to the right tertiary facilities across districts.",
    btn_login_here: "Login Here",
    btn_explore_matrix: "Explore Live Matrix",
    btn_explore_platform: "Explore Platform",
    active_monitoring: "Active Monitoring",
    operational_fidelity: "Network Operational Fidelity",
    clinical_quote: "Advancing maternal outcomes through clinical machine intelligence and regional infrastructure routing.",
    network_state_optimal: "Network State: Optimal Transit Readiness",

    // System Capabilities
    sys_cap_title: "Comprehensive System Capabilities",
    sys_cap_subtitle: "Modular intelligence designed for clinical precision and operational scale.",
    cap_ai_title: "AI Risk Assessment",
    cap_ai_desc: "Predictive modeling identifying high-risk pregnancies before complications arise, ensuring proactive clinical intervention.",
    cap_hosp_title: "Hospital Network Intelligence",
    cap_hosp_desc: "Real-time mapping of facility capabilities, bed availability, and specialized care units across regions.",
    cap_route_title: "Smart Routing",
    cap_route_desc: "Algorithmic patient transfer protocols optimizing distance, urgency, and specific facility readiness.",
    cap_cmd_title: "Real-Time Command Center",
    cap_cmd_desc: "A centralized, high-fidelity overview for administrators to monitor regional maternal health logistics instantly.",

    // Login Page
    login_title: "MaatriMarg",
    login_subtitle: "Secure access to Maharashtra & Tamil Nadu Maternal Healthcare Intelligence Platform.",
    clinician_id_label: "Clinician / Employee ID",
    clinician_id_placeholder: "e.g. MH-DOC-8492 or Mobile Number",
    security_key_label: "Security Key / Password",
    security_key_placeholder: "Enter secure access key",
    forgot_key: "Forgot Key?",
    verify_device: "Verify device for 30 days",
    btn_authenticate: "Authenticate Access",
    encrypted_session: "End-to-End Encrypted Session",
    tab_asha: "ASHA / ANM",
    tab_cmo: "Hospital CMO",
    tab_dho: "DHO Command",

    // Command Center
    cmd_header_title: "Real-time Maternal Logistics Command",
    cmd_header_subtitle: "MaatriMarg System Overview • Active Routing Matrix across Maharashtra & Tamil Nadu",
    net_efficiency: "Network Efficiency",
    active_dispatches: "Active Dispatches",
    icu_available: "Available ICU Beds",
    critical_diversions: "Critical Diversions",
    btn_topography: "Topography",
    btn_satellite: "Satellite",
    search_hospitals_ph: "Search hospitals, districts...",
    btn_watchdog: "Auto-Escalate Watchdog",
    active_missions_title: "Active Missions",
    telemetry_table_title: "Hospital Telemetry & Capacity Grid",

    // Hospitals Directory
    hosp_title: "Hospitals & Facilities Directory",
    hosp_subtitle: "Real-time bed availability, specialized neonatal ICU, and blood bank reserves across 165 government hospitals.",
    filter_state: "State",
    filter_district: "District",
    total_facilities: "Total Facilities",
    icu_nicu_beds: "ICU & NICU Beds Available",
    blood_units_o_neg: "Blood Units (O- Negative Reserve)",
    btn_update_capacity: "+ Update Facility Capacity",
    col_facility: "FACILITY NAME",
    col_district: "DISTRICT & STATE",
    col_status: "STATUS",
    col_gen_beds: "GEN BEDS",
    col_nicu_beds: "NICU BEDS",
    col_surgeon: "SURGEON ON DUTY",
    col_actions: "ACTIONS",
    btn_edit_capacity: "Edit Live Capacity",

    // Maternal Risk Assessment Form
    maternal_title: "Maternal Risk Assessment",
    maternal_subtitle: "Real-time clinical data entry and ML-driven risk evaluation.",
    clinical_entry_title: "Clinical Data Entry",
    clinical_entry_sub: "Enter current maternal measurements.",
    btn_load_sample: "Load Sample Data",
    btn_reset_form: "Reset Form",
    btn_predict_risk: "Predict Risk",
    input_age: "Age",
    input_hr: "Heart Rate",
    input_sbp: "Systolic BP",
    input_dbp: "Diastolic BP",
    input_bs: "Blood Sugar (BS)",
    input_temp: "Body Temp",
    unit_years: "Years",
    unit_bpm: "bpm",
    unit_mmhg: "mmHg",
    unit_mmol: "mmol/L",
    unit_deg_f: "°F",
    assessment_result_title: "Assessment Result",
    no_assessment_yet: "No assessment yet. Enter the maternal measurements and select Predict Risk to calculate the current risk.",
    triage_tier: "Triage Tier",
    risk_score: "Risk Score",
    contributing_factors: "Contributing Factors",
    optimal_hospital: "Optimal Hospital Destination",

    // Hospital Dashboard extras
    status_online: "ONLINE",
    status_active: "Active",
    status_standby: "Standby",
    capacity_increase: "+12% capacity",
    live_synced: "Live synced",
    all_states: "All States",
    all_districts: "All Districts",
    avail_gen_beds: "Available General Beds",
    nicu_icu_units: "NICU / ICU Units Available",
    o_pos_blood: "O+ Blood Stock",
    o_neg_blood: "O- Blood Reserve",
    surgeon_on_duty: "Surgeon On Duty",
    confirm_capacity_update: "Confirm Live Capacity Update",
    saving: "Saving...",
    in_transit: "in transit",
    beds_reserved: "beds reserved",
    divert_active: "divert active",
    total_beds: "Total Beds",
    icu_nicu: "ICU / NICU",
    blood_units: "Blood Units",
    active_nodes: "Active Nodes",
    scanning_grid: "Scanning Grid...",
    audit_grid: "Audit Grid Protocol",
    core_system_portals: "CORE SYSTEM PORTALS",
    system_support: "SYSTEM & SUPPORT",
    clinical_platform: "Clinical Platform",

    // Chronic Portal
    chronic_title: "Cardiovascular Disease ML Risk Calculator",
    chronic_subtitle: "Rural NCD risk assessment evaluating BMI, BP stages, cholesterol, and lifestyle risk factors against trained clinical models.",
    chronic_banner_tag: "Cardiovascular & NCD Screening Network",
    chronic_form_title: "Biometrics & Lifestyle Input",
    chronic_form_sub: "Adult NCD risk screening parameters",
    input_height: "Height (cm)",
    input_weight: "Weight (kg)",
    input_cholesterol: "Cholesterol Level",
    input_glucose: "Glucose Level",
    chol_normal: "1 - Normal (< 200 mg/dL)",
    chol_above: "2 - Above Normal (200-239)",
    chol_high: "3 - Well Above Normal (≥ 240)",
    gluc_normal: "1 - Normal (< 140 mg/dL)",
    gluc_above: "2 - Above Normal (140-199)",
    gluc_high: "3 - Well Above Normal (≥ 200)",
    tobacco: "Tobacco",
    alcohol: "Alcohol",
    physically_active: "Active",
    btn_calc_cvd: "Calculate Cardiovascular Risk",
    evaluating_model: "Evaluating Model...",
    cvd_scorecard: "CARDIOVASCULAR SCORECARD",
    cvd_probability: "CVD Risk Probability",
    clinical_guidance: "Clinical Management Guidance",
    awaiting_cvd: "Awaiting Cardiovascular Inputs",
    awaiting_cvd_desc: "Fill the form on the left to calculate CVD probability percentage and recommended clinical protocols.",
    register_patient: "+ Register Patient",
    register_ncd_patient: "Register NCD Patient",
    patient_full_name: "Patient Full Name",
    age_years: "Age in Years",
    gender: "Gender",
    male: "Male",
    female: "Female",
    village_ward: "Village / Ward",
    register_for_screening: "Register Patient for Screening",

    // Child Portal
    child_title: "Pediatric Triage & Longitudinal Vitals",
    child_subtitle: "Age-banded pediatric triage engine evaluating Respiratory Rate, Heart Rate, SpO2, and Core Temperature against VIPER clinical rules.",
    child_banner_tag: "Pediatric VIPER Triage & Child Health Hub",
    child_form_title: "Pediatric Vitals Entry",
    child_form_sub: "Record infant vitals (0 to 60 months)",
    input_age_months: "Age in Months",
    input_spo2: "SpO2 Level (%)",
    input_rr: "Respiratory Rate (bpm)",
    input_hr_child: "Heart Rate (bpm)",
    input_temp_c: "Body Temperature (°C)",
    btn_run_viper: "Run VIPER Pediatric Triage",
    evaluating_viper: "Evaluating VIPER Engine...",
    viper_outcome: "VIPER TRIAGE OUTCOME",
    shock_index: "Pediatric Shock / Sepsis Index",
    action_protocol: "Action Protocol",
    awaiting_peds: "Awaiting Pediatric Vitals",
    awaiting_peds_desc: "Select a child and enter vitals to evaluate against the VIPER pediatric triage engine.",
    register_child: "+ Register Child",
    register_ped_patient: "Register Pediatric Patient",
    child_name: "Child Name",
    parent_guardian: "Parent / Guardian Name",

    // Maternal Portal extras
    on_field_duty: "On Field Duty",
    standby_mode: "Standby Mode",
    gps_geotag: "GPS Geotag",
    auto_geotag_active: "Auto-Geotag Active",
    sos_broadcasting: "SOS BEACON BROADCASTING",
    trigger_sos: "Trigger Emergency SOS",
    dho_oversight: "District Command Supervisory & Clinical Protocol Review",
    executive_mode: "Executive Mode",
    logged_in_as: "Logged in as",
    return_gis: "Return to Live GIS Matrix",
    hospital_triage: "Tertiary Hospital Inpatient & Emergency Triage Evaluation",
    clinical_specialist: "Clinical Specialist",
    hospital_dir_link: "Hospital Directory",
    awaiting_clinical: "Awaiting Clinical Input",
    awaiting_clinical_desc: "Fill the vitals form on the left or click 'Load Sample Data' to run real-time inference.",
    clinical_triage_outcome: "CLINICAL TRIAGE OUTCOME",
    confidence_score: "Confidence Score",
    recommended_protocol: "Recommended Protocol",
    risk_high: "High Risk",
    risk_mid: "Mid Risk",
    risk_low: "Low Risk",
    auto_priority_108: "Auto-Priority: 108 Emergency Route Locked",
    view_matrix: "View Matrix",
    google_maps: "Google Maps",
    live_route: "LIVE ROUTE",
    device_gps: "Device GPS",
    est_transit: "ESTIMATED TRANSIT",
    distance: "DISTANCE",
    avail_icu_beds: "AVAILABLE ICU BEDS",
    tertiary_regional: "TERTIARY REGIONAL",

    // Footer
    footer_tagline: "© 2026 MaatriMarg AI. Clinical Precision, Human Care. • Smart India Hackathon PS 26133",
    terms_of_service: "Terms of Service",
    data_privacy: "Data Privacy",
    contact_admin: "Contact System Admin",
    support: "Help & Protocol Support",
    back_to_landing: "Back to Landing",
    logout_session: "Log Out Session"
  },

  mr: {
    analytics: "प्रादेशिक विश्लेषण व उष्णता नकाशा",
    admin_governance: "प्रशासन व नियंत्रण केंद्र",
    maternal_analytics_tab: "माता आरोग्य विश्लेषण",
    pediatric_analytics_tab: "बालक व नवजात शिशु विश्लेषण",
    live_epidemiology: "थेट साथीचे विश्लेषण",
    master_controls: "मुख्य नियंत्रणे",
    time_24h: "२४ तास",
    time_7d: "७ दिवस",
    time_30d: "३० दिवस",
    time_ytd: "वार्षिक (YTD)",
    maternal_screenings: "माता तपासण्या",
    pediatric_screenings: "बालक तपासण्या",
    avg_time_to_care: "सरासरी उपचार वेळ",
    ml_prediction_accuracy: "AI अंदाज अचूकता",
    district_risk_stratification: "जिल्हानिहाय जोखीम व ICU ताण निर्देशांक",
    district_pediatric_stratification: "जिल्हानिहाय बालक जोखीम व NICU निर्देशांक",
    primary_maternal_risk_drivers: "प्रमुख माता आरोग्य जोखीम घटक",
    primary_pediatric_risk_drivers: "प्रमुख बालक आरोग्य जोखीम घटक",
    recent_case_outcomes: "अलीकडील अति-जोखीम रुग्ण निकाल व परिणामकारकता",
    recent_peds_outcomes: "अलीकडील बालक आपत्कालीन संदर्भ व SNCU निकाल",
    gateway_uptime: "गेटवे सक्रियता वेळ",
    ml_latency: "AI वेग (लॅटन्सी)",
    active_websockets: "सक्रिय वेबसॉकेट्स",
    emergency_queue: "आपत्कालीन राउटिंग रांग",
    tab_audit_trail: "मास्टर ऑडिट नोंदी",
    tab_regional_governance: "प्रादेशिक राउटिंग नियम",
    tab_clinician_roles: "डॉक्टर व आरोग्य कर्मचारी अधिकार",
    btn_export_audit: "ऑडिट नोंदी डाउनलोड करा",
    btn_broadcast_alert: "आपत्कालीन अलर्ट प्रसारित करा",
    filter_severity: "तीव्रतेनुसार फिल्टर करा",
    all_divisions: "सर्व विभाग",
    case_id: "केस आयडी",
    receiving_facility: "स्वीकारणारे रुग्णालय",
    time_to_care: "उपचार वेळ",
    clinical_outcome: "वैद्यकीय निकाल",

    dashboard: "कमांड सेंटर",
    hospitals: "रुग्णालये",
    maternal_portal: "माता पोर्टल",
    child_portal: "बालक पोर्टल",
    chronic_portal: "जुनाट आजार पोर्टल",
    live_gis_matrix: "थेट वैद्यकीय GIS मॅट्रिक्स",
    asha_agents: "आशा सेविका",
    active_fleet: "108 सक्रिय वाहने",
    routing_dispatch: "राउटिंग इंटेलिजेंस आणि डिस्पेच",
    starting_point: "१. सुरुवातीचे ठिकाण",
    home_address: "घर / पत्ता",
    live_gps_device: "थेट जीपीएस स्थान",
    dest_hospital: "२. गंतव्य रुग्णालय",
    auto_selected_nearest: "स्वयंचलितपणे सर्वात जवळचे निवडले",
    optimal_referral: "इष्टतम संदर्भ",
    standby_receiving: "स्टँडबाय रुग्णालये",
    dispatch_ambulance: "108 रुग्णवाहिका पाठवा",
    filters_label: "फिल्टर",
    // Nav & Brand
    app_title: "मात्रीमार्ग",
    tagline: "राष्ट्रीय माता व बालक आपत्कालीन आरोग्य नेटवर्क",
    national_command: "राष्ट्रीय कमांड नेटवर्क सक्रिय • महाराष्ट्र व तामिळनाडू",
    home_sos_route: "घरून थेट रुग्णालय मार्ग (गुगल मॅप्स)",
    clinician_login_btn: "वैद्यकीय लॉगिन",
    dho_hq: "जिल्हा आरोग्य मुख्यालय (DHO)",

    // Landing Page
    hero_headline_1: "माता आरोग्य",
    hero_headline_2: "अल्गोरिदम व बुद्धिमत्ता प्रणाली",
    hero_subtitle: "वैद्यकीय जोखीम आधीच ओळखा. थेट आयसीयू बेड वाटप आणि ग्रामीण भागातील मातांसाठी सुवर्ण तासाचे (Golden Hour) तत्काळ संरक्षण.",
    btn_login_here: "येथे लॉगिन करा",
    btn_explore_matrix: "थेट नेटवर्क पहा",
    btn_explore_platform: "प्लॅटफॉर्म पहा",
    active_monitoring: "थेट देखरेख",
    operational_fidelity: "नेटवर्क कार्यक्षमता",
    clinical_quote: "अचूक मशीन लर्निंग आणि प्रादेशिक रुग्णालय समन्वयातून माता व बालकांचे प्राण वाचवणे.",
    network_state_optimal: "नेटवर्क स्थिती: पूर्णतः सज्ज",

    // System Capabilities
    sys_cap_title: "प्रणालीची सर्वंकष वैशिष्ट्ये",
    sys_cap_subtitle: "वैद्यकीय अचूकता आणि आपत्कालीन सेवेसाठी अत्याधुनिक मॉड्यूलर तंत्रज्ञान.",
    cap_ai_title: "AI जोखीम मूल्यांकन",
    cap_ai_desc: "गुंतागुंत निर्माण होण्यापूर्वीच उच्च-जोखीम गर्भधारणा ओळखणारे अचूक प्रेडिक्टिव मॉडेल.",
    cap_hosp_title: "रुग्णालय नेटवर्क माहिती",
    cap_hosp_desc: "जिल्ह्यातील सर्व रुग्णालयांची क्षमता, उपलब्ध बेड्स, NICU आणि रक्तसाठ्याची थेट माहिती.",
    cap_route_title: "स्मार्ट मार्गनिर्देशन",
    cap_route_desc: "अंतर, रुग्णाची निकड आणि उपलब्ध शस्त्रक्रिया तज्ज्ञांनुसार सर्वात जलद रुग्णालयाची निवड.",
    cap_cmd_title: "थेट कमांड सेंटर",
    cap_cmd_desc: "जिल्हाधिकाऱ्यांना आणि आरोग्य प्रमुखांना संपूर्ण जिल्ह्याची आरोग्य परिस्थिती एकाच पडद्यावर दाखवणारे कमांड सेंटर.",

    // Login Page
    login_title: "मात्रीमार्ग",
    login_subtitle: "महाराष्ट्र व तामिळनाडू माता आरोग्य कमांड प्रणालीत सुरक्षित प्रवेश.",
    clinician_id_label: "आरोग्य सेवक / डॉक्टर आयडी",
    clinician_id_placeholder: "उदा. MH-DOC-8492 किंवा मोबाईल नंबर",
    security_key_label: "सुरक्षा पासवर्ड / पिन",
    security_key_placeholder: "सुरक्षित पासवर्ड टाका",
    forgot_key: "पासवर्ड विसरलात?",
    verify_device: "हे उपकरण ३० दिवसांसाठी सत्यापित ठेवा",
    btn_authenticate: "प्रणालीत प्रवेश करा",
    encrypted_session: "संपूर्ण सुरक्षित व एनक्रिप्टेड सत्र",
    tab_asha: "आशा / एएनएम",
    tab_cmo: "रुग्णालय CMO",
    tab_dho: "जिल्हा कमांड (DHO)",

    // Command Center
    cmd_header_title: "थेट माता आरोग्य व रुग्णवाहिका कमांड सेंटर",
    cmd_header_subtitle: "मात्रीमार्ग प्रणाली आढावा • महाराष्ट्र व तामिळनाडू सक्रिय मार्गनिर्देशन",
    net_efficiency: "नेटवर्क कार्यक्षमता",
    active_dispatches: "सक्रिय रुग्णवाहिका",
    icu_available: "उपलब्ध आयसीयू खाटा",
    critical_diversions: "अति-तातडीचे अलर्ट",
    btn_topography: "भूप्रदेश नकाशा",
    btn_satellite: "उपग्रह नकाशा",
    search_hospitals_ph: "रुग्णालये किंवा जिल्हे शोधा...",
    btn_watchdog: "स्वयंचलित पाठपुरावा वॉचडॉग",
    active_missions_title: "सक्रिय मोहिमा",
    telemetry_table_title: "रुग्णालय क्षमता व थेट माहिती तक्ता",

    // Hospitals Directory
    hosp_title: "शासकीय रुग्णालये व आरोग्य केंद्र निर्देशिका",
    hosp_subtitle: "१६५ सरकारी रुग्णालयातील उपलब्ध बेड्स, नवजात शिशु NICU आणि रक्तपेढी साठ्याची थेट माहिती.",
    filter_state: "राज्य",
    filter_district: "जिल्हा",
    total_facilities: "एकूण रुग्णालये",
    icu_nicu_beds: "उपलब्ध ICU व NICU खाटा",
    blood_units_o_neg: "रक्त साठा (O- निगेटिव्ह राखीव)",
    btn_update_capacity: "+ क्षमता अद्ययावत करा",
    col_facility: "रुग्णालयाचे नाव",
    col_district: "जिल्हा व राज्य",
    col_status: "स्थिती",
    col_gen_beds: "सामान्य खाटा",
    col_nicu_beds: "NICU खाटा",
    col_surgeon: "उपलब्ध सर्जन",
    col_actions: "क्रिया",
    btn_edit_capacity: "माहिती बदला",

    // Maternal Risk Assessment Form
    maternal_title: "माता आरोग्य जोखीम तपासणी",
    maternal_subtitle: "थेट वैद्यकीय नोंदी आणि AI आधारित जोखीम मूल्यांकन.",
    clinical_entry_title: "वैद्यकीय नोंदी प्रविष्ट करा",
    clinical_entry_sub: "मातेचे सध्याचे आरोग्य मोजमाप नोंदवा.",
    btn_load_sample: "नमुना माहिती भरा",
    btn_reset_form: "फॉर्म रीसेट करा",
    btn_predict_risk: "जोखीम तपासा",
    input_age: "वय",
    input_hr: "हृदयाचे ठोके",
    input_sbp: "सिस्टोलिक रक्तदाब",
    input_dbp: "डायस्टोलिक रक्तदाब",
    input_bs: "रक्तातील साखर (BS)",
    input_temp: "शरीराचे तापमान",
    unit_years: "वर्षे",
    unit_bpm: "ठोके/मि",
    unit_mmhg: "mmHg",
    unit_mmol: "mmol/L",
    unit_deg_f: "°F",
    assessment_result_title: "तपासणी निकाल",
    no_assessment_yet: "अद्याप तपासणी झालेली नाही. मातेचे आरोग्य मोजमाप भरून 'जोखीम तपासा' वर क्लिक करा.",
    triage_tier: "ट्रायज स्तर",
    risk_score: "जोखीम गुण",
    contributing_factors: "कारणीभूत घटक",
    optimal_hospital: "योग्य रुग्णालय गंतव्य",


    // Hospital Dashboard extras
    status_online: "ऑनलाइन",
    status_active: "सक्रिय",
    status_standby: "स्टँडबाय",
    capacity_increase: "+12% क्षमता",
    live_synced: "थेट सिंक",
    all_states: "सर्व राज्ये",
    all_districts: "सर्व जिल्हे",
    avail_gen_beds: "उपलब्ध सामान्य खाटा",
    nicu_icu_units: "NICU / ICU युनिट उपलब्ध",
    o_pos_blood: "O+ रक्त साठा",
    o_neg_blood: "O- रक्त राखीव",
    surgeon_on_duty: "कर्तव्यावर सर्जन",
    confirm_capacity_update: "क्षमता अद्ययावत निश्चित करा",
    saving: "जतन होत आहे...",
    in_transit: "मार्गावर",
    beds_reserved: "खाटा आरक्षित",
    divert_active: "डायव्हर्ट सक्रिय",
    total_beds: "एकूण खाटा",
    icu_nicu: "ICU / NICU",
    blood_units: "रक्त युनिट",
    active_nodes: "सक्रिय केंद्रे",
    scanning_grid: "ग्रिड स्कॅन होत आहे...",
    audit_grid: "ग्रिड ऑडिट प्रोटोकॉल",
    core_system_portals: "मुख्य प्रणाली पोर्टल",
    system_support: "प्रणाली व सहाय्य",
    clinical_platform: "वैद्यकीय प्रणाली",
    // Chronic Portal
    chronic_title: "हृदय रोग ML जोखीम कॅल्क्युलेटर",
    chronic_subtitle: "ग्रामीण NCD जोखीम मूल्यांकन - BMI, रक्तदाब, कोलेस्ट्रॉल आणि जीवनशैली जोखीम घटकांचे विश्लेषण.",
    chronic_banner_tag: "हृदय रोग व NCD स्क्रीनिंग नेटवर्क",
    chronic_form_title: "बायोमेट्रिक्स व जीवनशैली इनपुट",
    chronic_form_sub: "प्रौढ NCD जोखीम स्क्रीनिंग पॅरामीटर",
    input_height: "उंची (सेमी)",
    input_weight: "वजन (किलो)",
    input_cholesterol: "कोलेस्ट्रॉल स्तर",
    input_glucose: "ग्लुकोज स्तर",
    chol_normal: "1 - सामान्य (< 200 mg/dL)",
    chol_above: "2 - सामान्यापेक्षा जास्त (200-239)",
    chol_high: "3 - खूप जास्त (≥ 240)",
    gluc_normal: "1 - सामान्य (< 140 mg/dL)",
    gluc_above: "2 - सामान्यापेक्षा जास्त (140-199)",
    gluc_high: "3 - खूप जास्त (≥ 200)",
    tobacco: "तंबाखू",
    alcohol: "मद्यपान",
    physically_active: "सक्रिय",
    btn_calc_cvd: "हृदय रोग जोखीम गणना करा",
    evaluating_model: "मॉडेल मूल्यांकन होत आहे...",
    cvd_scorecard: "हृदय रोग स्कोरकार्ड",
    cvd_probability: "CVD जोखीम शक्यता",
    clinical_guidance: "वैद्यकीय व्यवस्थापन मार्गदर्शन",
    awaiting_cvd: "हृदय डेटाची प्रतीक्षा",
    awaiting_cvd_desc: "CVD शक्यता टक्केवारी आणि शिफारसींसाठी डाव्या बाजूचा फॉर्म भरा.",
    register_patient: "+ रुग्ण नोंदणी",
    register_ncd_patient: "NCD रुग्ण नोंदणी",
    patient_full_name: "रुग्णाचे पूर्ण नाव",
    age_years: "वय (वर्षे)",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    village_ward: "गाव / प्रभाग",
    register_for_screening: "स्क्रीनिंगसाठी रुग्ण नोंदवा",
    // Child Portal
    child_title: "बालक ट्रायज व दीर्घकालीन तपासणी",
    child_subtitle: "VIPER नियमांनुसार श्वसन दर, हृदयगती, SpO2 आणि तापमान यांचे वय-आधारित बालक ट्रायज.",
    child_banner_tag: "बालक VIPER ट्रायज व आरोग्य केंद्र",
    child_form_title: "बालक आरोग्य नोंदी",
    child_form_sub: "अर्भकाचे आरोग्य मोजमाप नोंदवा (0 ते 60 महिने)",
    input_age_months: "वय (महिने)",
    input_spo2: "SpO2 स्तर (%)",
    input_rr: "श्वसन दर (bpm)",
    input_hr_child: "हृदयगती (bpm)",
    input_temp_c: "शरीराचे तापमान (°C)",
    btn_run_viper: "VIPER बालक ट्रायज चालवा",
    evaluating_viper: "VIPER इंजिन मूल्यांकन होत आहे...",
    viper_outcome: "VIPER ट्रायज निकाल",
    shock_index: "बालक शॉक / सेप्सिस निर्देशांक",
    action_protocol: "कारवाई प्रोटोकॉल",
    awaiting_peds: "बालक आरोग्य नोंदींची प्रतीक्षा",
    awaiting_peds_desc: "मूल निवडा आणि VIPER बालक ट्रायज इंजिनमध्ये मूल्यांकनासाठी नोंदी भरा.",
    register_child: "+ मूल नोंदणी",
    register_ped_patient: "बालक रुग्ण नोंदणी",
    child_name: "मुलाचे नाव",
    parent_guardian: "पालक / संरक्षक नाव",
    // Maternal Portal extras
    on_field_duty: "फील्ड ड्युटीवर",
    standby_mode: "स्टँडबाय मोड",
    gps_geotag: "GPS जिओटॅग",
    auto_geotag_active: "ऑटो-जिओटॅग सक्रिय",
    sos_broadcasting: "SOS बीकन प्रसारित होत आहे",
    trigger_sos: "आपत्कालीन SOS सक्रिय करा",
    dho_oversight: "जिल्हा कमांड पर्यवेक्षण व वैद्यकीय प्रोटोकॉल पुनरावलोकन",
    executive_mode: "कार्यकारी मोड",
    logged_in_as: "म्हणून लॉगिन",
    return_gis: "थेट GIS मॅट्रिक्सवर परत जा",
    hospital_triage: "तृतीयक रुग्णालय आंतररुग्ण व आपत्कालीन ट्रायज मूल्यांकन",
    clinical_specialist: "वैद्यकीय तज्ज्ञ",
    hospital_dir_link: "रुग्णालय निर्देशिका",
    awaiting_clinical: "वैद्यकीय नोंदींची प्रतीक्षा",
    awaiting_clinical_desc: "थेट अनुमान चालवण्यासाठी डाव्या बाजूचा फॉर्म भरा किंवा 'नमुना डेटा' वर क्लिक करा.",
    clinical_triage_outcome: "वैद्यकीय ट्रायज निकाल",
    confidence_score: "विश्वास गुण",
    recommended_protocol: "शिफारसी प्रोटोकॉल",
    risk_high: "उच्च जोखीम",
    risk_mid: "मध्यम जोखीम",
    risk_low: "कमी जोखीम",
    auto_priority_108: "स्वयं-प्राधान्य: 108 आपत्कालीन मार्ग लॉक",
    view_matrix: "मॅट्रिक्स पहा",
    google_maps: "गुगल मॅप्स",
    live_route: "थेट मार्ग",
    device_gps: "उपकरण GPS",
    est_transit: "अंदाजित पारगमन",
    distance: "अंतर",
    avail_icu_beds: "उपलब्ध ICU खाटा",
    tertiary_regional: "तृतीयक प्रादेशिक",
    // Footer
    footer_tagline: "© २०२६ मात्रीमार्ग AI. अचूक वैद्यकीय सेवा, मानवी काळजी. • स्मार्ट इंडिया हॅकाथॉन",
    terms_of_service: "सेवा अटी",
    data_privacy: "माहिती गोपनीयता",
    contact_admin: "प्रणाली व्यवस्थापकाशी संपर्क",
    support: "मदत व आपत्कालीन सहाय्य",
    back_to_landing: "मुख्य पृष्ठावर जा",
    logout_session: "सत्र समाप्त करा (लॉगआउट)"
  },

  hi: {
    analytics: "क्षेत्रीय विश्लेषण एवं हीटमैप",
    admin_governance: "प्रशासन एवं नियंत्रण केंद्र",
    maternal_analytics_tab: "मातृ स्वास्थ्य विश्लेषण",
    pediatric_analytics_tab: "बालक एवं नवजात शिशु विश्लेषण",
    live_epidemiology: "लाइव महामारी विज्ञान",
    master_controls: "मुख्य नियंत्रण",
    time_24h: "24 घंटे",
    time_7d: "7 दिन",
    time_30d: "30 दिन",
    time_ytd: "वार्षिक (YTD)",
    maternal_screenings: "मातृ स्वास्थ्य जांच",
    pediatric_screenings: "बालक स्वास्थ्य जांच",
    avg_time_to_care: "औसत उपचार समय",
    ml_prediction_accuracy: "AI पूर्वानुमान सटीकता",
    district_risk_stratification: "जिलावार जोखिम एवं ICU तनाव सूचकांक",
    district_pediatric_stratification: "जिलावार बालक जोखिम एवं NICU सूचकांक",
    primary_maternal_risk_drivers: "प्रमुख मातृ जोखिम कारक",
    primary_pediatric_risk_drivers: "प्रमुख बालक जोखिम कारक",
    recent_case_outcomes: "हाल के उच्च-जोखिम मामले एवं रेफरल प्रभावशीलता",
    recent_peds_outcomes: "हाल के आपातकालीन बालक ट्रांसफर एवं SNCU परिणाम",
    gateway_uptime: "गेटवे अपटाइम",
    ml_latency: "AI लेटेंसी (गति)",
    active_websockets: "सक्रिय वेबसॉकेट",
    emergency_queue: "आपातकालीन रूटिंग कतार",
    tab_audit_trail: "मास्टर ऑडिट ट्रेल",
    tab_regional_governance: "क्षेत्रीय रूटिंग नियम",
    tab_clinician_roles: "चिकित्सक एवं एक्सेस रोल",
    btn_export_audit: "ऑडिट लॉग निर्यात करें",
    btn_broadcast_alert: "आपातकालीन अलर्ट प्रसारित करें",
    filter_severity: "गंभीरता अनुसार फ़िल्टर",
    all_divisions: "सभी संभाग",
    case_id: "केस आईडी",
    receiving_facility: "प्राप्तकर्ता अस्पताल",
    time_to_care: "उपचार समय",
    clinical_outcome: "नैदानिक परिणाम",

    dashboard: "कमांड सेंटर",
    hospitals: "अस्पताल निर्देशिका",
    maternal_portal: "मातृ पोर्टल",
    child_portal: "बालक पोर्टल (VIPER)",
    chronic_portal: "गंभीर रोग (NCD) पोर्टल",
    live_gis_matrix: "लाइव चिकित्सा जीआईएस मैट्रिक्स",
    asha_agents: "आशा कार्यकत्री",
    active_fleet: "108 सक्रिय वाहन",
    routing_dispatch: "रूटिंग इंटेलिजेंस और डिस्पैच",
    starting_point: "१. प्रारंभिक बिंदु",
    home_address: "घर / पता",
    live_gps_device: "लाइव जीपीएस स्थान",
    dest_hospital: "२. गंतव्य अस्पताल",
    auto_selected_nearest: "स्वतः चयनित निकटतम",
    optimal_referral: "इष्टतम रेफ़रल",
    standby_receiving: "स्टैंडबाय अस्पताल",
    dispatch_ambulance: "108 एम्बुलेंस भेजें",
    filters_label: "फ़िल्टर",
    // Nav & Brand
    app_title: "मातृमार्ग",
    tagline: "राष्ट्रीय मातृ एवं आपातकालीन स्वास्थ्य नेटवर्क",
    national_command: "राष्ट्रीय कमान नेटवर्क सक्रिय • महाराष्ट्र एवं तमिलनाडु",
    home_sos_route: "घर से अस्पताल सीधा मार्ग (गूगल मैप्स)",
    clinician_login_btn: "चिकित्सकीय लॉगिन",
    dho_hq: "जिला स्वास्थ्य मुख्यालय (DHO)",

    // Landing Page
    hero_headline_1: "मातृ स्वास्थ्य",
    hero_headline_2: "कृत्रिम बुद्धिमत्ता मंच",
    hero_subtitle: "सटीक जोखिम जांच, वास्तविक समय आईसीयू बेड आवंटन, एवं ग्रामीण भारत में माताओं के लिए गोल्डन आवर की संपूर्ण सुरक्षा।",
    btn_login_here: "यहाँ लॉगिन करें",
    btn_explore_matrix: "लाइव नेटवर्क देखें",
    btn_explore_platform: "मंच देखें",
    active_monitoring: "सक्रिय निगरानी",
    operational_fidelity: "नेटवर्क विश्वसनीयता",
    clinical_quote: "मशीन इंटेलिजेंस और क्षेत्रीय अस्पताल समन्वय द्वारा मातृ एवं शिशु मृत्यु दर में रोकथाम।",
    network_state_optimal: "नेटवर्क स्थिति: पूर्णतः तत्पर",

    // System Capabilities
    sys_cap_title: "प्रणाली की संपूर्ण क्षमताएं",
    sys_cap_subtitle: "चिकित्सकीय सटीकता और आपातकालीन प्रतिक्रिया के लिए आधुनिक मॉड्यूलर तकनीक।",
    cap_ai_title: "AI जोखिम मूल्यांकन",
    cap_ai_desc: "जटिलताओं के उभरने से पहले ही उच्च जोखिम वाली गर्भावस्था की पहचान करने वाला पूर्वानुमान मॉडल।",
    cap_hosp_title: "अस्पताल नेटवर्क इंटेलिजेंस",
    cap_hosp_desc: "क्षेत्र भर में उपलब्ध सामान्य बेड, एनआईसीयू बेड और ब्लड बैंक स्टॉक का वास्तविक समय मानचित्रण।",
    cap_route_title: "स्मार्ट अस्पताल रूटिंग",
    cap_route_desc: "दूरी, मरीज की स्थिति और सर्जन उपलब्धता के आधार पर सबसे उपयुक्त निकटतम अस्पताल का चयन।",
    cap_cmd_title: "रियल-टाइम कमांड सेंटर",
    cap_cmd_desc: "प्रशासकों और मुख्य चिकित्सा अधिकारियों के लिए संपूर्ण जिले की स्वास्थ्य स्थिति का केंद्रीय अवलोकन।",

    // Login Page
    login_title: "मातृमार्ग",
    login_subtitle: "महाराष्ट्र एवं तमिलनाडु मातृ स्वास्थ्य कमान मंच में सुरक्षित प्रवेश।",
    clinician_id_label: "स्वास्थ्य कार्यकर्ता / डॉक्टर आईडी",
    clinician_id_placeholder: "उदा. MH-DOC-8492 या मोबाइल नंबर",
    security_key_label: "सुरक्षा पासवर्ड / पिन",
    security_key_placeholder: "सुरक्षित पासवर्ड दर्ज करें",
    forgot_key: "पासवर्ड भूल गए?",
    verify_device: "इस उपकरण को 30 दिनों के लिए सत्यापित रखें",
    btn_authenticate: "प्रणाली में प्रवेश करें",
    encrypted_session: "एंड-टू-एंड एन्क्रिप्टेड सत्र",
    tab_asha: "आशा / एएनएम",
    tab_cmo: "अस्पताल सीएमओ",
    tab_dho: "जिला कमान (DHO)",

    // Command Center
    cmd_header_title: "रियल-टाइम मातृ लॉजिस्टिक्स कमांड सेंटर",
    cmd_header_subtitle: "मातृमार्ग प्रणाली अवलोकन • सक्रिय अस्पताल एवं एम्बुलेंस मार्गनिर्देशन",
    net_efficiency: "नेटवर्क दक्षता",
    active_dispatches: "सक्रिय एम्बुलेंस",
    icu_available: "उपलब्ध आईसीयू बेड",
    critical_diversions: "आपातकालीन अलर्ट",
    btn_topography: "भौगोलिक नक्शा",
    btn_satellite: "सैटेलाइट नक्शा",
    search_hospitals_ph: "अस्पताल या जिला खोजें...",
    btn_watchdog: "स्वतः एस्केलेशन वॉचडॉग",
    active_missions_title: "सक्रिय मिशन",
    telemetry_table_title: "अस्पताल क्षमता एवं लाइव डेटा तालिका",

    // Hospitals Directory
    hosp_title: "शासकीय अस्पताल एवं स्वास्थ्य केंद्र निर्देशिका",
    hosp_subtitle: "165 सरकारी अस्पतालों में उपलब्ध सामान्य बेड, नवजात शिशु NICU और ब्लड बैंक स्टॉक की लाइव जानकारी।",
    filter_state: "राज्य",
    filter_district: "जिला",
    total_facilities: "कुल अस्पताल",
    icu_nicu_beds: "उपलब्ध ICU एवं NICU बेड",
    blood_units_o_neg: "रक्त स्टॉक (O- नेगेटिव आरक्षित)",
    btn_update_capacity: "+ क्षमता अपडेट करें",
    col_facility: "अस्पताल का नाम",
    col_district: "जिला एवं राज्य",
    col_status: "स्थिति",
    col_gen_beds: "सामान्य बेड",
    col_nicu_beds: "NICU बेड",
    col_surgeon: "उपलब्ध सर्जन",
    col_actions: "क्रियाएं",
    btn_edit_capacity: "विवरण संपादित करें",

    // Maternal Risk Assessment Form
    maternal_title: "मातृ स्वास्थ्य जोखिम मूल्यांकन",
    maternal_subtitle: "वास्तविक समय डेटा प्रविष्टि और AI आधारित जोखिम विश्लेषण।",
    clinical_entry_title: "स्वास्थ्य डेटा प्रविष्टि",
    clinical_entry_sub: "माता के वर्तमान स्वास्थ्य माप दर्ज करें।",
    btn_load_sample: "नमूना डेटा लोड करें",
    btn_reset_form: "फॉर्म रीसेट करें",
    btn_predict_risk: "जोखिम जांचें",
    input_age: "आयु",
    input_hr: "हृदय गति",
    input_sbp: "सिस्टोलिक रक्तचाप",
    input_dbp: "डायस्टोलिक रक्तचाप",
    input_bs: "रक्त शर्करा (BS)",
    input_temp: "शरीर का तापमान",
    unit_years: "वर्ष",
    unit_bpm: "धड़कन/मिनट",
    unit_mmhg: "mmHg",
    unit_mmol: "mmol/L",
    unit_deg_f: "°F",
    assessment_result_title: "मूल्यांकन परिणाम",
    no_assessment_yet: "अभी तक कोई परीक्षण नहीं हुआ है। स्वास्थ्य माप दर्ज करें और 'जोखिम जांचें' चुनें।",
    triage_tier: "ट्राइएज श्रेणी",
    risk_score: "जोखिम स्कोर",
    contributing_factors: "प्रमुख कारक",
    optimal_hospital: "अनुशंसित अस्पताल गंतव्य",


    // Hospital Dashboard extras
    status_online: "ऑनलाइन",
    status_active: "सक्रिय",
    status_standby: "स्टैंडबाय",
    capacity_increase: "+12% क्षमता",
    live_synced: "लाइव सिंक्ड",
    all_states: "सभी राज्य",
    all_districts: "सभी जिले",
    avail_gen_beds: "उपलब्ध सामान्य बेड",
    nicu_icu_units: "NICU / ICU यूनिट उपलब्ध",
    o_pos_blood: "O+ रक्त स्टॉक",
    o_neg_blood: "O- रक्त आरक्षित",
    surgeon_on_duty: "ड्यूटी पर सर्जन",
    confirm_capacity_update: "क्षमता अपडेट की पुष्टि करें",
    saving: "सहेज रहा है...",
    in_transit: "पारगमन में",
    beds_reserved: "बेड आरक्षित",
    divert_active: "डायवर्ट सक्रिय",
    total_beds: "कुल बेड",
    icu_nicu: "ICU / NICU",
    blood_units: "रक्त इकाइयां",
    active_nodes: "सक्रिय केंद्र",
    scanning_grid: "ग्रिड स्कैन हो रहा है...",
    audit_grid: "ग्रिड ऑडिट प्रोटोकॉल",
    core_system_portals: "मुख्य प्रणाली पोर्टल",
    system_support: "प्रणाली एवं सहायता",
    clinical_platform: "चिकित्सा मंच",
    // Chronic Portal
    chronic_title: "हृदय रोग ML जोखिम कैलकुलेटर",
    chronic_subtitle: "ग्रामीण NCD जोखिम मूल्यांकन - BMI, रक्तचाप, कोलेस्ट्रॉल और जीवनशैली जोखिम कारकों का विश्लेषण।",
    chronic_banner_tag: "हृदय रोग एवं NCD स्क्रीनिंग नेटवर्क",
    chronic_form_title: "बायोमेट्रिक्स एवं जीवनशैली इनपुट",
    chronic_form_sub: "वयस्क NCD जोखिम स्क्रीनिंग पैरामीटर",
    input_height: "ऊंचाई (सेमी)",
    input_weight: "वजन (किग्रा)",
    input_cholesterol: "कोलेस्ट्रॉल स्तर",
    input_glucose: "ग्लूकोज स्तर",
    chol_normal: "1 - सामान्य (< 200 mg/dL)",
    chol_above: "2 - सामान्य से अधिक (200-239)",
    chol_high: "3 - बहुत अधिक (≥ 240)",
    gluc_normal: "1 - सामान्य (< 140 mg/dL)",
    gluc_above: "2 - सामान्य से अधिक (140-199)",
    gluc_high: "3 - बहुत अधिक (≥ 200)",
    tobacco: "तंबाकू",
    alcohol: "शराब",
    physically_active: "सक्रिय",
    btn_calc_cvd: "हृदय रोग जोखिम गणना करें",
    evaluating_model: "मॉडल मूल्यांकन हो रहा है...",
    cvd_scorecard: "हृदय रोग स्कोरकार्ड",
    cvd_probability: "CVD जोखिम प्रायिकता",
    clinical_guidance: "चिकित्सा प्रबंधन मार्गदर्शन",
    awaiting_cvd: "हृदय डेटा की प्रतीक्षा",
    awaiting_cvd_desc: "CVD प्रायिकता प्रतिशत और अनुशंसित चिकित्सा प्रोटोकॉल की गणना के लिए बाईं ओर फॉर्म भरें।",
    register_patient: "+ मरीज पंजीकरण",
    register_ncd_patient: "NCD मरीज पंजीकरण",
    patient_full_name: "मरीज का पूरा नाम",
    age_years: "आयु (वर्ष)",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    village_ward: "गांव / वार्ड",
    register_for_screening: "स्क्रीनिंग के लिए मरीज पंजीकृत करें",
    // Child Portal
    child_title: "बालक ट्राइएज और दीर्घकालिक जांच",
    child_subtitle: "VIPER नैदानिक नियमों के आधार पर श्वसन दर, हृदय गति, SpO2 और तापमान का आयु-आधारित बालक ट्राइएज।",
    child_banner_tag: "बालक VIPER ट्राइएज और स्वास्थ्य केंद्र",
    child_form_title: "बालक महत्वपूर्ण संकेत प्रविष्टि",
    child_form_sub: "शिशु के संकेत दर्ज करें (0 से 60 महीने)",
    input_age_months: "आयु (महीनों में)",
    input_spo2: "SpO2 स्तर (%)",
    input_rr: "श्वसन दर (bpm)",
    input_hr_child: "हृदय गति (bpm)",
    input_temp_c: "शरीर का तापमान (°C)",
    btn_run_viper: "VIPER बालक ट्राइएज चलाएं",
    evaluating_viper: "VIPER इंजन मूल्यांकन हो रहा है...",
    viper_outcome: "VIPER ट्राइएज परिणाम",
    shock_index: "बालक शॉक / सेप्सिस सूचकांक",
    action_protocol: "कार्रवाई प्रोटोकॉल",
    awaiting_peds: "बालक संकेतों की प्रतीक्षा",
    awaiting_peds_desc: "एक बच्चा चुनें और VIPER बालक ट्राइएज इंजन के विरुद्ध मूल्यांकन के लिए संकेत दर्ज करें।",
    register_child: "+ बच्चा पंजीकरण",
    register_ped_patient: "बालक रोगी पंजीकरण",
    child_name: "बच्चे का नाम",
    parent_guardian: "अभिभावक / संरक्षक का नाम",
    // Maternal Portal extras
    on_field_duty: "फील्ड ड्यूटी पर",
    standby_mode: "स्टैंडबाय मोड",
    gps_geotag: "GPS जियोटैग",
    auto_geotag_active: "ऑटो-जियोटैग सक्रिय",
    sos_broadcasting: "SOS बीकन प्रसारित हो रहा है",
    trigger_sos: "आपातकालीन SOS सक्रिय करें",
    dho_oversight: "जिला कमान पर्यवेक्षण एवं चिकित्सा प्रोटोकॉल समीक्षा",
    executive_mode: "कार्यकारी मोड",
    logged_in_as: "के रूप में लॉगिन",
    return_gis: "लाइव GIS मैट्रिक्स पर लौटें",
    hospital_triage: "तृतीयक अस्पताल आंतरिक रोगी एवं आपातकालीन ट्राइएज मूल्यांकन",
    clinical_specialist: "चिकित्सा विशेषज्ञ",
    hospital_dir_link: "अस्पताल निर्देशिका",
    awaiting_clinical: "नैदानिक इनपुट की प्रतीक्षा",
    awaiting_clinical_desc: "वास्तविक समय अनुमान चलाने के लिए बाईं ओर का फॉर्म भरें या 'नमूना डेटा लोड करें' पर क्लिक करें।",
    clinical_triage_outcome: "नैदानिक ट्राइएज परिणाम",
    confidence_score: "विश्वास स्कोर",
    recommended_protocol: "अनुशंसित प्रोटोकॉल",
    risk_high: "उच्च जोखिम",
    risk_mid: "मध्यम जोखिम",
    risk_low: "कम जोखिम",
    auto_priority_108: "स्वतः-प्राथमिकता: 108 आपातकालीन मार्ग लॉक",
    view_matrix: "मैट्रिक्स देखें",
    google_maps: "गूगल मैप्स",
    live_route: "लाइव मार्ग",
    device_gps: "डिवाइस GPS",
    est_transit: "अनुमानित पारगमन",
    distance: "दूरी",
    avail_icu_beds: "उपलब्ध ICU बेड",
    tertiary_regional: "तृतीयक क्षेत्रीय",
    // Footer
    footer_tagline: "© 2026 मातृमार्ग AI. चिकित्सकीय सटीकता, मानवीय देखभाल। • स्मार्ट इंडिया हैकथॉन",
    terms_of_service: "सेवा की शर्तें",
    data_privacy: "डेटा गोपनीयता",
    contact_admin: "प्रणाली व्यवस्थापक से संपर्क",
    support: "सहायता एवं आपातकालीन सपोर्ट",
    back_to_landing: "मुख्य पृष्ठ पर लौटें",
    logout_session: "लॉग आउट करें"
  },

  ta: {
    analytics: "பிராந்திய பகுப்பாய்வு & வெப்ப வரைபடம்",
    admin_governance: "நிர்வாகம் & ஆளுகை மையம்",
    maternal_analytics_tab: "தாய்வழி நலம் பகுப்பாய்வு",
    pediatric_analytics_tab: "குழந்தை மற்றும் பிறந்த குழந்தை பகுப்பாய்வு",
    live_epidemiology: "நேரடி தொற்றுநோயியல்",
    master_controls: "முதன்மை கட்டுப்பாடுகள்",
    time_24h: "24 மணி நேரம்",
    time_7d: "7 நாட்கள்",
    time_30d: "30 நாட்கள்",
    time_ytd: "ஆண்டு மொத்தம் (YTD)",
    maternal_screenings: "தாய்வழி பரிசோதனைகள்",
    pediatric_screenings: "குழந்தை பரிசோதனைகள்",
    avg_time_to_care: "சராசரி சிகிச்சை நேரம்",
    ml_prediction_accuracy: "AI முன்கணிப்பு துல்லியம்",
    district_risk_stratification: "மாவட்ட வாரியான ஆபத்து & ICU அழுத்த குறியீடு",
    district_pediatric_stratification: "மாவட்ட வாரியான குழந்தை ஆபத்து & NICU குறியீடு",
    primary_maternal_risk_drivers: "முக்கிய தாய்வழி ஆபத்து காரணிகள்",
    primary_pediatric_risk_drivers: "முக்கிய குழந்தை ஆபத்து காரணிகள்",
    recent_case_outcomes: "அண்மைக்கால அதிக ஆபத்துள்ள பரிந்துரைகள் & முடிவுகள்",
    recent_peds_outcomes: "அண்மைக்கால குழந்தை அவசர பரிந்துரைகள் & SNCU முடிவுகள்",
    gateway_uptime: "கேட்வே இயக்க நேரம்",
    ml_latency: "AI தாமதம் (வேகம்)",
    active_websockets: "செயலில் உள்ள வெப்சாக்கெட்ஸ்",
    emergency_queue: "அவசர ரூட்டிங் வரிசை",
    tab_audit_trail: "முதன்மை தணிக்கை பதிவு",
    tab_regional_governance: "பிராந்திய ரூட்டிங் விதிகள்",
    tab_clinician_roles: "மருத்துவர்கள் & அணுகல் பாத்திரங்கள்",
    btn_export_audit: "தணிக்கை பதிவுகளை பதிவிறக்குக",
    btn_broadcast_alert: "அவசர எச்சரிக்கையை ஒளிபரப்பு",
    filter_severity: "தீவிரத்தின் அடிப்படையில் வடிகட்டவும்",
    all_divisions: "அனைத்து மண்டலங்கள்",
    case_id: "வழக்கு ஐடி",
    receiving_facility: "பெறும் மருத்துவமனை",
    time_to_care: "சிகிச்சை நேரம்",
    clinical_outcome: "மருத்துவ முடிவு",

    dashboard: "கட்டுப்பாட்டு அறை",
    hospitals: "மருத்துவமனைகள்",
    maternal_portal: "தாய்மை பக்கம்",
    child_portal: "குழந்தை பக்கம்",
    chronic_portal: "நாள்பட்ட நோய் பக்கம்",
    live_gis_matrix: "நேரடி மருத்துவ GIS மேட்ரிக்ஸ்",
    asha_agents: "ஆஷா பணியாளர்கள்",
    active_fleet: "108 ஆம்புலன்ஸ்கள்",
    routing_dispatch: "ரூட்டிங் உளவுத்துறை மற்றும் அனுப்புதல்",
    starting_point: "1. தொடக்கப் புள்ளி",
    home_address: "வீடு / முகவரி",
    live_gps_device: "நேரடி ஜிபிஎஸ் இருப்பிடம்",
    dest_hospital: "2. சேருமிட மருத்துவமனை",
    auto_selected_nearest: "தானாக தேர்ந்தெடுக்கப்பட்ட அருகில்",
    optimal_referral: "உகந்த பரிந்துரை",
    standby_receiving: "காத்திருப்பு மருத்துவமனைகள்",
    dispatch_ambulance: "108 ஆம்புலன்ஸை அனுப்பு",
    filters_label: "வடிகட்டிகள்",
    // Nav & Brand
    app_title: "மாத்ரிமார்க்",
    tagline: "தேசிய தாய் மற்றும் அவசர சிகிச்சை AI நெட்வொர்க்",
    national_command: "தேசிய கட்டளை நெட்வொர்க் செயலில் உள்ளது • மகாராஷ்டிரா & தமிழ்நாடு",
    home_sos_route: "வீட்டிலிருந்து நேரடி அவசர பாதை (Google Maps)",
    clinician_login_btn: "மருத்துவர் உள்நுழைவு",
    dho_hq: "மாவட்ட சுகாதார தலைமையகம் (DHO)",

    // Landing Page
    hero_headline_1: "தாய்வழி நலம்",
    hero_headline_2: "நுண்ணறிவு தளம்",
    hero_subtitle: "மருத்துவ ஆபத்தை முன்கூட்டியே கணிக்கவும். நிகழ்நேர ஐசியூ படுக்கை ஒதுக்கீடு மற்றும் அவசர காலங்களில் தாய்மார்களுக்கான நேரடி ஆம்புலன்ஸ் வழிகாட்டல்.",
    btn_login_here: "இங்கே உள்நுழைக",
    btn_explore_matrix: "நேரடி நெட்வொர்க் காண்க",
    btn_explore_platform: "தளத்தை ஆராய்க",
    active_monitoring: "நேரடி கண்காணிப்பு",
    operational_fidelity: "நெட்வொர்க் செயல்திறன்",
    clinical_quote: "மருத்துவ நுண்ணறிவு மற்றும் பிராந்திய மருத்துவமனை ஒருங்கிணைப்பு மூலம் தாய் மற்றும் சிசு மரணங்களைத் தடுத்தல்.",
    network_state_optimal: "நெட்வொர்க் நிலை: முழு தயார்நிலை",

    // System Capabilities
    sys_cap_title: "கட்டமைப்பின் முழுமையான திறன்கள்",
    sys_cap_subtitle: "மருத்துவ துல்லியம் மற்றும் அவசர கால விரைவுச் செயல்பாட்டிற்கான நவீன தொழில்நுட்பம்.",
    cap_ai_title: "AI ஆபத்து மதிப்பீடு",
    cap_ai_desc: "சிக்கல்கள் தோன்றுவதற்கு முன்பே அதிக ஆபத்துள்ள கர்ப்பங்களை முன்கூட்டியே கண்டறியும் முன்கணிப்பு மாதிரி.",
    cap_hosp_title: "மருத்துவமனை நெட்வொர்க் நுண்ணறிவு",
    cap_hosp_desc: "படுக்கை இருப்பு, பிரசவ தீவிர சிகிச்சைப் பிரிவு (NICU) மற்றும் இரத்த வங்கி இருப்பின் நிகழ்நேர வரைபடம்.",
    cap_route_title: "ஸ்மார்ட் மருத்துவமனை ரூட்டிங்",
    cap_route_desc: "தூரம், நோயாளியின் நிலை மற்றும் அறுவை சிகிச்சை நிபுணர் தயார்நிலையின் அடிப்படையில் சிறந்த மருத்துவமனை தேர்வு.",
    cap_cmd_title: "நிகழ்நேர கட்டளை மையம்",
    cap_cmd_desc: "நிர்வாகிகள் மற்றும் மாவட்ட சுகாதார அதிகாரிகளுக்கு பிராந்திய சுகாதார தளவாடங்களை உடனுக்குடன் கண்காணிக்கும் மேடை.",

    // Login Page
    login_title: "மாத்ரிமார்க்",
    login_subtitle: "மகாராஷ்டிரா மற்றும் தமிழ்நாடு தாய்வழி நலம் கட்டளை அமைப்பில் பாதுகாப்பான நுழைவு.",
    clinician_id_label: "சுகாதார பணியாளர் / மருத்துவர் ஐடி",
    clinician_id_placeholder: "எ.கா. MH-DOC-8492 அல்லது மொபைல் எண்",
    security_key_label: "பாதுகாப்பு கடவுச்சொல் / பின்",
    security_key_placeholder: "பாதுகாப்பான கடவுச்சொல்லை உள்ளிடவும்",
    forgot_key: "கடவுச்சொல் மறந்துவிட்டதா?",
    verify_device: "இந்த சாதனத்தை 30 நாட்களுக்கு நினைவில் கொள்க",
    btn_authenticate: "அமைப்பில் உள்நுழைக",
    encrypted_session: "முழுமையான மறைகுறியாக்கப்பட்ட அமர்வு",
    tab_asha: "ஆஷா / கிராம செவிலியர்",
    tab_cmo: "மருத்துவமனை CMO",
    tab_dho: "மாவட்ட கட்டளை (DHO)",

    // Command Center
    cmd_header_title: "நிகழ்நேர தாய்வழி சுகாதார கட்டளை மையம்",
    cmd_header_subtitle: "மாத்ரிமார்க் அமைப்பு கண்ணோட்டம் • நேரடி மருத்துவமனை மற்றும் ஆம்புலன்ஸ் வழிகாட்டல்",
    net_efficiency: "நெட்வொர்க் திறன்",
    active_dispatches: "செயலில் உள்ள ஆம்புலன்ஸ்கள்",
    icu_available: "கிடைக்கும் ICU படுக்கைகள்",
    critical_diversions: "அவசர கால எச்சரிக்கைகள்",
    btn_topography: "நிலப்பரப்பு வரைபடம்",
    btn_satellite: "செயற்கைக்கோள் வரைபடம்",
    search_hospitals_ph: "மருத்துவமனை அல்லது மாவட்டத்தைத் தேடுக...",
    btn_watchdog: "தானியங்கி மேலனுப்பீடு வாட்ச்டாக்",
    active_missions_title: "செயலில் உள்ள பணிகள்",
    telemetry_table_title: "மருத்துவமனை திறன் மற்றும் நேரடி தரவு அட்டவணை",

    // Hospitals Directory
    hosp_title: "அரசு மருத்துவமனைகள் அடைவு",
    hosp_subtitle: "165 அரசு மருத்துவமனைகளில் படுக்கை இருப்பு, பச்சிளங்குழந்தை NICU மற்றும் இரத்த வங்கி இருப்பு நேரடி தகவல்.",
    filter_state: "மாநிலம்",
    filter_district: "மாவட்டம்",
    total_facilities: "மொத்த மருத்துவமனைகள்",
    icu_nicu_beds: "கிடைக்கும் ICU மற்றும் NICU படுக்கைகள்",
    blood_units_o_neg: "இரத்த இருப்பு (O- நெகட்டிவ் இருப்பு)",
    btn_update_capacity: "+ படுக்கை விவரம் புதுப்பிக்க",
    col_facility: "மருத்துவமனை பெயர்",
    col_district: "மாவட்டம் மற்றும் மாநிலம்",
    col_status: "நிலை",
    col_gen_beds: "பொது படுக்கைகள்",
    col_nicu_beds: "NICU படுக்கைகள்",
    col_surgeon: "அறுவை சிகிச்சை நிபுணர்",
    col_actions: "செயல்கள்",
    btn_edit_capacity: "திறனை மாற்று",

    // Maternal Risk Assessment Form
    maternal_title: "தாய்வழி நலம் ஆபத்து மதிப்பீடு",
    maternal_subtitle: "நிகழ்நேர மருத்துவத் தரவு உள்ளீடு மற்றும் AI ஆபத்து பகுப்பாய்வு.",
    clinical_entry_title: "மருத்துவத் தரவு உள்ளீடு",
    clinical_entry_sub: "தாயின் தற்போதைய மருத்துவ அளவீடுகளை உள்ளிடவும்.",
    btn_load_sample: "மாதிரித் தரவை நிரப்புக",
    btn_reset_form: "படிவத்தை மீட்டமை",
    btn_predict_risk: "ஆபத்தை மதிப்பிடுக",
    input_age: "வயது",
    input_hr: "இதயத் துடிப்பு",
    input_sbp: "சிஸ்டாலிக் இரத்த அழுத்தம்",
    input_dbp: "டயஸ்டாலிக் இரத்த அழுத்தம்",
    input_bs: "இரத்த சர்க்கரை (BS)",
    input_temp: "உடல் வெப்பநிலை",
    unit_years: "வருடம்",
    unit_bpm: "துடிப்பு/நிமி",
    unit_mmhg: "mmHg",
    unit_mmol: "mmol/L",
    unit_deg_f: "°F",
    assessment_result_title: "பகுப்பாய்வு முடிவு",
    no_assessment_yet: "இதுவரை பரிசோதனை செய்யப்படவில்லை. அளவீடுகளை உள்ளிட்டு 'ஆபத்தை மதிப்பிடுக' பொத்தானை அழுத்தவும்.",
    triage_tier: "அவசர நிலை வகை",
    risk_score: "ஆபத்து மதிப்பீடு",
    contributing_factors: "முக்கிய காரணிகள்",
    optimal_hospital: "பரிந்துரைக்கப்பட்ட மருத்துவமனை",


    // Hospital Dashboard extras
    status_online: "ஆன்லைன்",
    status_active: "செயலில்",
    status_standby: "காத்திருப்பு",
    capacity_increase: "+12% திறன்",
    live_synced: "நேரடி ஒத்திசைவு",
    all_states: "அனைத்து மாநிலங்கள்",
    all_districts: "அனைத்து மாவட்டங்கள்",
    avail_gen_beds: "கிடைக்கும் பொது படுக்கைகள்",
    nicu_icu_units: "NICU / ICU யூனிட்கள் கிடைக்கின்றன",
    o_pos_blood: "O+ இரத்த இருப்பு",
    o_neg_blood: "O- இரத்த ஒதுக்கீடு",
    surgeon_on_duty: "கடமையில் அறுவை சிகிச்சை நிபுணர்",
    confirm_capacity_update: "திறன் புதுப்பிப்பை உறுதிப்படுத்தவும்",
    saving: "சேமிக்கிறது...",
    in_transit: "போக்குவரத்தில்",
    beds_reserved: "படுக்கைகள் ஒதுக்கப்பட்டன",
    divert_active: "திருப்புதல் செயலில்",
    total_beds: "மொத்த படுக்கைகள்",
    icu_nicu: "ICU / NICU",
    blood_units: "இரத்த அலகுகள்",
    active_nodes: "செயலில் உள்ள மையங்கள்",
    scanning_grid: "கிரிட் ஸ்கேன் ஆகிறது...",
    audit_grid: "கிரிட் ஆடிட் நெறிமுறை",
    core_system_portals: "முக்கிய அமைப்பு பக்கங்கள்",
    system_support: "அமைப்பு மற்றும் ஆதரவு",
    clinical_platform: "மருத்துவ தளம்",
    // Chronic Portal
    chronic_title: "இதய நோய் ML ஆபத்து கால்குலேட்டர்",
    chronic_subtitle: "கிராமப்புற NCD ஆபத்து மதிப்பீடு - BMI, இரத்த அழுத்தம், கொழுப்பு மற்றும் வாழ்க்கைமுறை ஆபத்து காரணிகளின் பகுப்பாய்வு.",
    chronic_banner_tag: "இதய நோய் மற்றும் NCD திரையிடல் நெட்வொர்க்",
    chronic_form_title: "உயிரளவை மற்றும் வாழ்க்கைமுறை உள்ளீடு",
    chronic_form_sub: "வயது வந்தவர் NCD ஆபத்து திரையிடல் அளவுருக்கள்",
    input_height: "உயரம் (செமீ)",
    input_weight: "எடை (கிகி)",
    input_cholesterol: "கொழுப்பு நிலை",
    input_glucose: "குளுக்கோஸ் நிலை",
    chol_normal: "1 - சாதாரணம் (< 200 mg/dL)",
    chol_above: "2 - சாதாரணத்திற்கு மேல் (200-239)",
    chol_high: "3 - மிக அதிகம் (≥ 240)",
    gluc_normal: "1 - சாதாரணம் (< 140 mg/dL)",
    gluc_above: "2 - சாதாரணத்திற்கு மேல் (140-199)",
    gluc_high: "3 - மிக அதிகம் (≥ 200)",
    tobacco: "புகையிலை",
    alcohol: "மது",
    physically_active: "செயலில்",
    btn_calc_cvd: "இதய நோய் ஆபத்தை கணக்கிடுங்கள்",
    evaluating_model: "மாடல் மதிப்பீடு செய்யப்படுகிறது...",
    cvd_scorecard: "இதய நோய் ஸ்கோர்கார்டு",
    cvd_probability: "CVD ஆபத்து நிகழ்தகவு",
    clinical_guidance: "மருத்துவ மேலாண்மை வழிகாட்டுதல்",
    awaiting_cvd: "இதய தரவுக்காக காத்திருக்கிறது",
    awaiting_cvd_desc: "CVD நிகழ்தகவு சதவீதம் மற்றும் பரிந்துரைக்கப்பட்ட நெறிமுறைகளுக்கு இடது பக்க படிவத்தை நிரப்பவும்.",
    register_patient: "+ நோயாளி பதிவு",
    register_ncd_patient: "NCD நோயாளி பதிவு",
    patient_full_name: "நோயாளி முழுப் பெயர்",
    age_years: "வயது (வருடங்கள்)",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    village_ward: "கிராமம் / வார்டு",
    register_for_screening: "திரையிடலுக்கு நோயாளியைப் பதிவு செய்க",
    // Child Portal
    child_title: "குழந்தை நோய் வகைப்படுத்தல் மற்றும் நீண்ட கால பரிசோதனை",
    child_subtitle: "VIPER மருத்துவ விதிகளின் அடிப்படையில் சுவாச விகிதம், இதயத் துடிப்பு, SpO2 மற்றும் வெப்பநிலையின் வயது அடிப்படையிலான குழந்தை வகைப்படுத்தல்.",
    child_banner_tag: "குழந்தை VIPER வகைப்படுத்தல் மற்றும் நலம் மையம்",
    child_form_title: "குழந்தை முக்கிய அறிகுறிகள் உள்ளீடு",
    child_form_sub: "குழந்தை அறிகுறிகளை பதிவு செய்க (0 முதல் 60 மாதங்கள்)",
    input_age_months: "வயது (மாதங்கள்)",
    input_spo2: "SpO2 நிலை (%)",
    input_rr: "சுவாச விகிதம் (bpm)",
    input_hr_child: "இதயத் துடிப்பு (bpm)",
    input_temp_c: "உடல் வெப்பநிலை (°C)",
    btn_run_viper: "VIPER குழந்தை வகைப்படுத்தலை இயக்கு",
    evaluating_viper: "VIPER இயந்திரம் மதிப்பீடு செய்கிறது...",
    viper_outcome: "VIPER வகைப்படுத்தல் முடிவு",
    shock_index: "குழந்தை அதிர்ச்சி / செப்சிஸ் குறியீடு",
    action_protocol: "நடவடிக்கை நெறிமுறை",
    awaiting_peds: "குழந்தை அறிகுறிகளுக்காக காத்திருக்கிறது",
    awaiting_peds_desc: "ஒரு குழந்தையைத் தேர்ந்தெடுத்து VIPER இயந்திரத்தில் மதிப்பீடு செய்ய அறிகுறிகளை உள்ளிடவும்.",
    register_child: "+ குழந்தை பதிவு",
    register_ped_patient: "குழந்தை நோயாளி பதிவு",
    child_name: "குழந்தையின் பெயர்",
    parent_guardian: "பெற்றோர் / பாதுகாவலர் பெயர்",
    // Maternal Portal extras
    on_field_duty: "கள பணியில்",
    standby_mode: "காத்திருப்பு நிலை",
    gps_geotag: "GPS புவிக்குறி",
    auto_geotag_active: "தானியங்கி புவிக்குறி செயலில்",
    sos_broadcasting: "SOS பீக்கான் ஒளிபரப்பாகிறது",
    trigger_sos: "அவசர SOS செயல்படுத்து",
    dho_oversight: "மாவட்ட கட்டளை மேற்பார்வை மற்றும் மருத்துவ நெறிமுறை ஆய்வு",
    executive_mode: "நிர்வாக முறை",
    logged_in_as: "உள்நுழைந்தவர்",
    return_gis: "நேரடி GIS மேட்ரிக்ஸுக்குத் திரும்பு",
    hospital_triage: "மூன்றாம் நிலை மருத்துவமனை உள்நோயாளி மற்றும் அவசர வகைப்படுத்தல் மதிப்பீடு",
    clinical_specialist: "மருத்துவ நிபுணர்",
    hospital_dir_link: "மருத்துவமனை அடைவு",
    awaiting_clinical: "மருத்துவ உள்ளீட்டுக்காக காத்திருக்கிறது",
    awaiting_clinical_desc: "நிகழ்நேர அனுமானத்தை இயக்க இடது பக்க படிவத்தை நிரப்பவும் அல்லது 'மாதிரி தரவு' கிளிக் செய்யவும்.",
    clinical_triage_outcome: "மருத்துவ வகைப்படுத்தல் முடிவு",
    confidence_score: "நம்பிக்கை மதிப்பெண்",
    recommended_protocol: "பரிந்துரைக்கப்பட்ட நெறிமுறை",
    risk_high: "அதிக ஆபத்து",
    risk_mid: "நடுத்தர ஆபத்து",
    risk_low: "குறைந்த ஆபத்து",
    auto_priority_108: "தானியங்கி-முன்னுரிமை: 108 அவசர பாதை பூட்டப்பட்டது",
    view_matrix: "மேட்ரிக்ஸ் காண்க",
    google_maps: "கூகிள் மேப்ஸ்",
    live_route: "நேரடி பாதை",
    device_gps: "சாதன GPS",
    est_transit: "மதிப்பிடப்பட்ட போக்குவரத்து",
    distance: "தூரம்",
    avail_icu_beds: "கிடைக்கும் ICU படுக்கைகள்",
    tertiary_regional: "மூன்றாம் நிலை பிராந்திய",
    // Footer
    footer_tagline: "© 2026 மாத்ரிமார்க் AI. மருத்துவ துல்லியம், மனிதப் பாதுகாப்பு. • ஸ்மார்ட் இந்தியா ஹேக்கத்தான்",
    terms_of_service: "சேவை விதிமுறைகள்",
    data_privacy: "தரவு தனியுரிமை",
    contact_admin: "அமைப்பு நிர்வாகியைத் தொடர்பு கொள்க",
    support: "உதவி மற்றும் அவசர ஆதரவு",
    back_to_landing: "முகப்புப் பக்கத்திற்குச் செல்",
    logout_session: "வெளியேறுக"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('maatrimarg_lang') || 'en';
  });

  const changeLanguage = (newLang) => {
    if (TRANSLATIONS[newLang]) {
      setLang(newLang);
      localStorage.setItem('maatrimarg_lang', newLang);
    }
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
